(*TOP*
 (item "Top")
 (chapter
  (item "ja/core_javascript_1.5_guide")
  (section
   (item "ja/core_javascript_1.5_guide/about")
   (item "ja/core_javascript_1.5_guide/block_statement")
   (item "ja/core_javascript_1.5_guide/calling_functions")
   (item "ja/core_javascript_1.5_guide/class-based_vs._prototype-based_languages")
   (item "ja/core_javascript_1.5_guide/comments")
   (item "ja/core_javascript_1.5_guide/conditional_statements")
   (item "ja/core_javascript_1.5_guide/constants")
   (item "ja/core_javascript_1.5_guide/core_language_features")
   (item "ja/core_javascript_1.5_guide/creating_a_regular_expression")
   (item "ja/core_javascript_1.5_guide/creating_new_objects")
   (subsection
    (item "ja/core_javascript_1.5_guide/creating_new_objects/defining_getters_and_setters")
    (item "ja/core_javascript_1.5_guide/creating_new_objects/defining_methods")
    (item "ja/core_javascript_1.5_guide/creating_new_objects/defining_properties_for_an_object_type")
    (item "ja/core_javascript_1.5_guide/creating_new_objects/deleting_properties")
    (item "ja/core_javascript_1.5_guide/creating_new_objects/indexing_object_properties")
    (item "ja/core_javascript_1.5_guide/creating_new_objects/using_a_constructor_function")
    (item "ja/core_javascript_1.5_guide/creating_new_objects/using_object_initializers")
    (item "ja/core_javascript_1.5_guide/creating_new_objects/using_this_for_object_references")
    )
   (item "ja/core_javascript_1.5_guide/defining_functions")
   (item "ja/core_javascript_1.5_guide/details_of_the_object_model")
   (item "ja/core_javascript_1.5_guide/domexception")
   (item "ja/core_javascript_1.5_guide/error")
   (item "ja/core_javascript_1.5_guide/evalerror")
   (item "ja/core_javascript_1.5_guide/exception_handling_statements")
   (subsection
    (item "ja/core_javascript_1.5_guide/exception_handling_statements/throw_statement")
    (item "ja/core_javascript_1.5_guide/exception_handling_statements/try...catch_statement")
    )
   (item "ja/core_javascript_1.5_guide/expressions")
   (item "ja/core_javascript_1.5_guide/expressions_and_operators")
   (item "ja/core_javascript_1.5_guide/functions")
   (item "ja/core_javascript_1.5_guide/inheritance")
   (item "ja/core_javascript_1.5_guide/iterators_and_generators")
   (item "ja/core_javascript_1.5_guide/javascript_overview")
   (item "ja/core_javascript_1.5_guide/literals")
   (item "ja/core_javascript_1.5_guide/liveconnect_overview")
   (subsection
    (item "ja/core_javascript_1.5_guide/liveconnect_overview/data_type_conversions")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/liveconnect_overview/data_type_conversions/java_to_javascript_conversions")
     (item "ja/core_javascript_1.5_guide/liveconnect_overview/data_type_conversions/javascript_to_java_conversions")
     )
    (item "ja/core_javascript_1.5_guide/liveconnect_overview/java_to_javascript_communication")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/liveconnect_overview/java_to_javascript_communication/using_the_liveconnect_classes")
     )
    (item "ja/core_javascript_1.5_guide/liveconnect_overview/javascript_to_java_communication")
    (item "ja/core_javascript_1.5_guide/liveconnect_overview/working_with_wrappers")
    )
   (item "ja/core_javascript_1.5_guide/loop_statements")
   (subsection
    (item "ja/core_javascript_1.5_guide/loop_statements/break_statement")
    (item "ja/core_javascript_1.5_guide/loop_statements/continue_statement")
    (item "ja/core_javascript_1.5_guide/loop_statements/do...while_statement")
    (item "ja/core_javascript_1.5_guide/loop_statements/for_statement")
    (item "ja/core_javascript_1.5_guide/loop_statements/label_statement")
    (item "ja/core_javascript_1.5_guide/loop_statements/while_statement")
    )
   (item "ja/core_javascript_1.5_guide/object_manipulation_statements")
   (item "ja/core_javascript_1.5_guide/objects_and_properties")
   (item "ja/core_javascript_1.5_guide/obsolete_pages")
   (subsection
    (item "ja/core_javascript_1.5_guide/obsolete_pages/block_statement")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/calling_functions")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/class-based_vs._prototype-based_languages")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/comments")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/conditional_statements")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/constants")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_a_regular_expression")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/defining_getters_and_setters")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/defining_methods")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/defining_properties_for_an_object_type")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/deleting_properties")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/indexing_object_properties")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/using_a_constructor_function")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/using_object_initializers")
     ;;(item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/using_this_for_object_references")
     )
    (item "ja/core_javascript_1.5_guide/obsolete_pages/data_type_conversions")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/data_type_conversions/java_to_javascript_conversions")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/data_type_conversions/javascript_to_java_conversions")
     )
    (item "ja/core_javascript_1.5_guide/obsolete_pages/defining_functions")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/exception_handling_statements")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/exception_handling_statements/throw_statement")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/exception_handling_statements/try...catch_statement")
     )
    (item "ja/core_javascript_1.5_guide/obsolete_pages/expressions")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/java_to_javascript_communication")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/java_to_javascript_communication/using_the_liveconnect_classes")
     )
    (item "ja/core_javascript_1.5_guide/obsolete_pages/javascript_to_java_communication")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/literals")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/break_statement")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/continue_statement")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/do...while_statement")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/for_statement")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/label_statement")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/while_statement")
     )
    (item "ja/core_javascript_1.5_guide/obsolete_pages/object_manipulation_statements")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/objects_and_properties")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/operators")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/arithmetic_operators")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/assignment_operators")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/bitwise_operators")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/comparison_operators")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/logical_operators")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/special_operators")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/string_operators")
     )
    (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/array_object")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/boolean_object")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/date_object")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/function_object")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/math_object")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/number_object")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/regexp_object")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/string_object")
     )
    (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/escape_and_unescape_functions")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/eval_function")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/isfinite_function")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/isnan_function")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/number_and_string_functions")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/parseint_and_parsefloat_functions")
     )
    (item "ja/core_javascript_1.5_guide/obsolete_pages/property_inheritance_revisited")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/property_inheritance_revisited/determining_instance_relationships")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/property_inheritance_revisited/global_information_in_constructors")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/property_inheritance_revisited/local_versus_inherited_values")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/property_inheritance_revisited/no_multiple_inheritance")
     )
    (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example/creating_the_hierarchy")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example/more_flexible_constructors")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example/object_properties")
     (subsubsubsection
      (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example/object_properties/adding_properties")
      (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example/object_properties/inheriting_properties")
      ))
    (item "ja/core_javascript_1.5_guide/obsolete_pages/unicode")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/using_the_arguments_object")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/values")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/variables")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/working_with_regular_expressions")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/obsolete_pages/working_with_regular_expressions/advanced_searching_with_flags")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/working_with_regular_expressions/examples_of_regular_expressions")
     (item "ja/core_javascript_1.5_guide/obsolete_pages/working_with_regular_expressions/using_parenthesized_substring_matches")
     )
    (item "ja/core_javascript_1.5_guide/obsolete_pages/working_with_wrappers")
    (item "ja/core_javascript_1.5_guide/obsolete_pages/writing_a_regular_expression_pattern")
    )
   (item "ja/core_javascript_1.5_guide/operators")
   (subsection
    (item "ja/core_javascript_1.5_guide/operators/arithmetic_operators")
    (item "ja/core_javascript_1.5_guide/operators/assignment_operators")
    (item "ja/core_javascript_1.5_guide/operators/bitwise_operators")
    (item "ja/core_javascript_1.5_guide/operators/comparison_operators")
    (item "ja/core_javascript_1.5_guide/operators/logical_operators")
    (item "ja/core_javascript_1.5_guide/operators/special_operators")
    (item "ja/core_javascript_1.5_guide/operators/string_operators")
    )
   (item "ja/core_javascript_1.5_guide/predefined_core_objects")
   (subsection
    (item "ja/core_javascript_1.5_guide/predefined_core_objects/array_object")
    (item "ja/core_javascript_1.5_guide/predefined_core_objects/boolean_object")
    (item "ja/core_javascript_1.5_guide/predefined_core_objects/date_object")
    (item "ja/core_javascript_1.5_guide/predefined_core_objects/function_object")
    (item "ja/core_javascript_1.5_guide/predefined_core_objects/math_object")
    (item "ja/core_javascript_1.5_guide/predefined_core_objects/number_object")
    (item "ja/core_javascript_1.5_guide/predefined_core_objects/regexp_object")
    (item "ja/core_javascript_1.5_guide/predefined_core_objects/string_object")
    )
   (item "ja/core_javascript_1.5_guide/predefined_functions")
   (subsection
    (item "ja/core_javascript_1.5_guide/predefined_functions/escape_and_unescape_functions")
    (item "ja/core_javascript_1.5_guide/predefined_functions/eval_function")
    (item "ja/core_javascript_1.5_guide/predefined_functions/isfinite_function")
    (item "ja/core_javascript_1.5_guide/predefined_functions/isnan_function")
    (item "ja/core_javascript_1.5_guide/predefined_functions/number_and_string_functions")
    (item "ja/core_javascript_1.5_guide/predefined_functions/parseint_and_parsefloat_functions")
    )
   (item "ja/core_javascript_1.5_guide/processing_xml_with_e4x")
   (item "ja/core_javascript_1.5_guide/property_inheritance_revisited")
   (subsection
    (item "ja/core_javascript_1.5_guide/property_inheritance_revisited/determining_instance_relationships")
    (item "ja/core_javascript_1.5_guide/property_inheritance_revisited/global_information_in_constructors")
    (item "ja/core_javascript_1.5_guide/property_inheritance_revisited/local_versus_inherited_values")
    (item "ja/core_javascript_1.5_guide/property_inheritance_revisited/no_multiple_inheritance")
    )
   (item "ja/core_javascript_1.5_guide/regular_expressions")
   (item "ja/core_javascript_1.5_guide/statements")
   (item "ja/core_javascript_1.5_guide/syntaxerror")
   (item "ja/core_javascript_1.5_guide/table_of_contents_1.0")
   (item "ja/core_javascript_1.5_guide/table_of_contents_2.0")
   (item "ja/core_javascript_1.5_guide/the_employee_example")
   (subsection
    (item "ja/core_javascript_1.5_guide/the_employee_example/creating_the_hierarchy")
    (item "ja/core_javascript_1.5_guide/the_employee_example/more_flexible_constructors")
    (item "ja/core_javascript_1.5_guide/the_employee_example/object_properties")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/the_employee_example/object_properties/adding_properties")
     (item "ja/core_javascript_1.5_guide/the_employee_example/object_properties/inheriting_properties")
     ))
   (item "ja/core_javascript_1.5_guide/typeerror")
   (item "ja/core_javascript_1.5_guide/unicode")
   (item "ja/core_javascript_1.5_guide/using_the_arguments_object")
   (item "ja/core_javascript_1.5_guide/values")
   (item "ja/core_javascript_1.5_guide/values__variables__and_literals")
   (item "ja/core_javascript_1.5_guide/variables")
   (item "ja/core_javascript_1.5_guide/working_with_arrays")
   (item "ja/core_javascript_1.5_guide/working_with_closures")
   (item "ja/core_javascript_1.5_guide/working_with_objects")
   (item "ja/core_javascript_1.5_guide/working_with_regular_expressions")
   (subsection
    (item "ja/core_javascript_1.5_guide/working_with_regular_expressions/advanced_searching_with_flags")
    (item "ja/core_javascript_1.5_guide/working_with_regular_expressions/examples_of_regular_expressions")
    (item "ja/core_javascript_1.5_guide/working_with_regular_expressions/using_parenthesized_substring_matches")
    )
   (item "ja/core_javascript_1.5_guide/writing_a_regular_expression_pattern")
   )
  (item "ja/core_javascript_1.5_reference")
  (section
   (item "ja/core_javascript_1.5_reference/about")
   (subsection
    (item "ja/core_javascript_1.5_reference/about/formatting_conventions")
    )
   (item "ja/core_javascript_1.5_reference/deprecated_features")
   (item "ja/core_javascript_1.5_reference/functions")
   (subsection
    (item "ja/core_javascript_1.5_reference/functions/arguments")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/functions/arguments/callee")
     (item "ja/core_javascript_1.5_reference/functions/arguments/caller")
     (item "ja/core_javascript_1.5_reference/functions/arguments/length")
     ))
   ;;(item "ja/core_javascript_1.5_reference/functions_and_function_scope")
   ;;(subsection
   ;;(item "ja/core_javascript_1.5_reference/functions_and_function_scope/arguments")
   ;;(subsubsection
   ;;(item "ja/core_javascript_1.5_reference/functions_and_function_scope/arguments/callee")
   ;;(item "ja/core_javascript_1.5_reference/functions_and_function_scope/arguments/caller")
   ;;(item "ja/core_javascript_1.5_reference/functions_and_function_scope/arguments/length")
   ;;))
   (item "ja/core_javascript_1.5_reference/global_functions")
   (subsection
    (item "ja/core_javascript_1.5_reference/global_functions/decodeuri")
    (item "ja/core_javascript_1.5_reference/global_functions/decodeuricomponent")
    (item "ja/core_javascript_1.5_reference/global_functions/encodeuri")
    (item "ja/core_javascript_1.5_reference/global_functions/encodeuricomponent")
    (item "ja/core_javascript_1.5_reference/global_functions/eval")
    (item "ja/core_javascript_1.5_reference/global_functions/isfinite")
    (item "ja/core_javascript_1.5_reference/global_functions/isnan")
    (item "ja/core_javascript_1.5_reference/global_functions/parsefloat")
    (item "ja/core_javascript_1.5_reference/global_functions/parseint")
    )
   (item "ja/core_javascript_1.5_reference/global_objects")
   (subsection
    (item "ja/core_javascript_1.5_reference/global_objects/array")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/array/concat")
     (item "ja/core_javascript_1.5_reference/global_objects/array/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/array/every")
     (item "ja/core_javascript_1.5_reference/global_objects/array/filter")
     (item "ja/core_javascript_1.5_reference/global_objects/array/foreach")
     (item "ja/core_javascript_1.5_reference/global_objects/array/index")
     (item "ja/core_javascript_1.5_reference/global_objects/array/indexof")
     (item "ja/core_javascript_1.5_reference/global_objects/array/input")
     (item "ja/core_javascript_1.5_reference/global_objects/array/join")
     (item "ja/core_javascript_1.5_reference/global_objects/array/lastindexof")
     (item "ja/core_javascript_1.5_reference/global_objects/array/length")
     (item "ja/core_javascript_1.5_reference/global_objects/array/map")
     (item "ja/core_javascript_1.5_reference/global_objects/array/pop")
     (item "ja/core_javascript_1.5_reference/global_objects/array/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/array/push")
     (item "ja/core_javascript_1.5_reference/global_objects/array/reduce")
     (item "ja/core_javascript_1.5_reference/global_objects/array/reduceright")
     (item "ja/core_javascript_1.5_reference/global_objects/array/reverse")
     (item "ja/core_javascript_1.5_reference/global_objects/array/shift")
     (item "ja/core_javascript_1.5_reference/global_objects/array/slice")
     (item "ja/core_javascript_1.5_reference/global_objects/array/some")
     (item "ja/core_javascript_1.5_reference/global_objects/array/sort")
     (item "ja/core_javascript_1.5_reference/global_objects/array/splice")
     (item "ja/core_javascript_1.5_reference/global_objects/array/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/array/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/array/unshift")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/boolean")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/boolean/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/boolean/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/boolean/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/boolean/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/boolean/valueof")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/date")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/date/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getdate")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getday")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getfullyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/gethours")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getmilliseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getminutes")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getmonth")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/gettime")
     (item "ja/core_javascript_1.5_reference/global_objects/date/gettimezoneoffset")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcdate")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcday")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcfullyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutchours")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcmilliseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcminutes")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcmonth")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/now")
     (item "ja/core_javascript_1.5_reference/global_objects/date/parse")
     (item "ja/core_javascript_1.5_reference/global_objects/date/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setdate")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setfullyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/sethours")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setmilliseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setminutes")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setmonth")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/settime")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcdate")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcfullyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutchours")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcmilliseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcminutes")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcmonth")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/todatestring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/togmtstring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tolocaledatestring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tolocaleformat")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tolocalestring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tolocaletimestring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/totimestring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/toutcstring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/utc")
     (item "ja/core_javascript_1.5_reference/global_objects/date/valueof")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/error")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/error/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/error/message")
     (item "ja/core_javascript_1.5_reference/global_objects/error/name")
     (item "ja/core_javascript_1.5_reference/global_objects/error/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/error/stack")
     (item "ja/core_javascript_1.5_reference/global_objects/error/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/error/tostring")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/evalerror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/evalerror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/evalerror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/evalerror/prototype")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/function")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/function/apply")
     (item "ja/core_javascript_1.5_reference/global_objects/function/arguments")
     (item "ja/core_javascript_1.5_reference/global_objects/function/arity")
     (item "ja/core_javascript_1.5_reference/global_objects/function/call")
     (item "ja/core_javascript_1.5_reference/global_objects/function/caller")
     (item "ja/core_javascript_1.5_reference/global_objects/function/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/function/length")
     (item "ja/core_javascript_1.5_reference/global_objects/function/name")
     (item "ja/core_javascript_1.5_reference/global_objects/function/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/function/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/function/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/function/valueof")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/java")
    (item "ja/core_javascript_1.5_reference/global_objects/javaarray")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/javaarray/length")
     (item "ja/core_javascript_1.5_reference/global_objects/javaarray/tostring")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/javaclass")
    (item "ja/core_javascript_1.5_reference/global_objects/javaobject")
    (item "ja/core_javascript_1.5_reference/global_objects/javapackage")
    (item "ja/core_javascript_1.5_reference/global_objects/math")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/math/abs")
     (item "ja/core_javascript_1.5_reference/global_objects/math/acos")
     (item "ja/core_javascript_1.5_reference/global_objects/math/asin")
     (item "ja/core_javascript_1.5_reference/global_objects/math/atan")
     (item "ja/core_javascript_1.5_reference/global_objects/math/atan2")
     (item "ja/core_javascript_1.5_reference/global_objects/math/ceil")
     (item "ja/core_javascript_1.5_reference/global_objects/math/cos")
     (item "ja/core_javascript_1.5_reference/global_objects/math/e")
     (item "ja/core_javascript_1.5_reference/global_objects/math/exp")
     (item "ja/core_javascript_1.5_reference/global_objects/math/floor")
     (item "ja/core_javascript_1.5_reference/global_objects/math/ln10")
     (item "ja/core_javascript_1.5_reference/global_objects/math/ln2")
     (item "ja/core_javascript_1.5_reference/global_objects/math/log")
     (item "ja/core_javascript_1.5_reference/global_objects/math/log10e")
     (item "ja/core_javascript_1.5_reference/global_objects/math/log2e")
     (item "ja/core_javascript_1.5_reference/global_objects/math/max")
     (item "ja/core_javascript_1.5_reference/global_objects/math/min")
     (item "ja/core_javascript_1.5_reference/global_objects/math/pi")
     (item "ja/core_javascript_1.5_reference/global_objects/math/pow")
     (item "ja/core_javascript_1.5_reference/global_objects/math/random")
     (item "ja/core_javascript_1.5_reference/global_objects/math/round")
     (item "ja/core_javascript_1.5_reference/global_objects/math/sin")
     (item "ja/core_javascript_1.5_reference/global_objects/math/sqrt")
     (item "ja/core_javascript_1.5_reference/global_objects/math/sqrt1_2")
     (item "ja/core_javascript_1.5_reference/global_objects/math/sqrt2")
     (item "ja/core_javascript_1.5_reference/global_objects/math/tan")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/netscape")
    (item "ja/core_javascript_1.5_reference/global_objects/number")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/number/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/number/max_value")
     (item "ja/core_javascript_1.5_reference/global_objects/number/min_value")
     (item "ja/core_javascript_1.5_reference/global_objects/number/nan")
     (item "ja/core_javascript_1.5_reference/global_objects/number/negative_infinity")
     (item "ja/core_javascript_1.5_reference/global_objects/number/positive_infinity")
     (item "ja/core_javascript_1.5_reference/global_objects/number/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/number/toexponential")
     (item "ja/core_javascript_1.5_reference/global_objects/number/tofixed")
     (item "ja/core_javascript_1.5_reference/global_objects/number/tolocalestring")
     (item "ja/core_javascript_1.5_reference/global_objects/number/toprecision")
     (item "ja/core_javascript_1.5_reference/global_objects/number/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/number/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/number/valueof")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/object")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/object/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/object/create")
     (item "ja/core_javascript_1.5_reference/global_objects/object/definegetter")
     (item "ja/core_javascript_1.5_reference/global_objects/object/defineproperties")
     (item "ja/core_javascript_1.5_reference/global_objects/object/defineproperty")
     (item "ja/core_javascript_1.5_reference/global_objects/object/definesetter")
     (item "ja/core_javascript_1.5_reference/global_objects/object/eval")
     (item "ja/core_javascript_1.5_reference/global_objects/object/getownpropertydescriptor")
     (item "ja/core_javascript_1.5_reference/global_objects/object/getprototypeof")
     (item "ja/core_javascript_1.5_reference/global_objects/object/hasownproperty")
     (item "ja/core_javascript_1.5_reference/global_objects/object/isprototypeof")
     (item "ja/core_javascript_1.5_reference/global_objects/object/keys")
     (item "ja/core_javascript_1.5_reference/global_objects/object/lookupgetter")
     (item "ja/core_javascript_1.5_reference/global_objects/object/lookupsetter")
     (item "ja/core_javascript_1.5_reference/global_objects/object/nosuchmethod")
     (item "ja/core_javascript_1.5_reference/global_objects/object/parent")
     (item "ja/core_javascript_1.5_reference/global_objects/object/propertyisenumerable")
     (item "ja/core_javascript_1.5_reference/global_objects/object/proto")
     (item "ja/core_javascript_1.5_reference/global_objects/object/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/object/temp")
     (item "ja/core_javascript_1.5_reference/global_objects/object/tolocalestring")
     (item "ja/core_javascript_1.5_reference/global_objects/object/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/object/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/object/unwatch")
     (item "ja/core_javascript_1.5_reference/global_objects/object/valueof")
     (item "ja/core_javascript_1.5_reference/global_objects/object/watch")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/packages")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/packages/classname")
     (item "ja/core_javascript_1.5_reference/global_objects/packages/java")
     (item "ja/core_javascript_1.5_reference/global_objects/packages/netscape")
     (item "ja/core_javascript_1.5_reference/global_objects/packages/sun")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/range")
    (item "ja/core_javascript_1.5_reference/global_objects/rangeerror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/rangeerror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/rangeerror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/rangeerror/prototype")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/referenceerror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/referenceerror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/referenceerror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/referenceerror/prototype")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/regexp")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/exec")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/global")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/ignorecase")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/lastindex")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/multiline")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/source")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/test")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/tostring")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/string")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/string/anchor")
     (item "ja/core_javascript_1.5_reference/global_objects/string/big")
     (item "ja/core_javascript_1.5_reference/global_objects/string/blink")
     (item "ja/core_javascript_1.5_reference/global_objects/string/bold")
     (item "ja/core_javascript_1.5_reference/global_objects/string/charat")
     (item "ja/core_javascript_1.5_reference/global_objects/string/charcodeat")
     (item "ja/core_javascript_1.5_reference/global_objects/string/concat")
     (item "ja/core_javascript_1.5_reference/global_objects/string/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/string/fixed")
     (item "ja/core_javascript_1.5_reference/global_objects/string/fontcolor")
     (item "ja/core_javascript_1.5_reference/global_objects/string/fontsize")
     (item "ja/core_javascript_1.5_reference/global_objects/string/fromcharcode")
     (item "ja/core_javascript_1.5_reference/global_objects/string/indexof")
     (item "ja/core_javascript_1.5_reference/global_objects/string/italics")
     (item "ja/core_javascript_1.5_reference/global_objects/string/lastindexof")
     (item "ja/core_javascript_1.5_reference/global_objects/string/length")
     (item "ja/core_javascript_1.5_reference/global_objects/string/link")
     (item "ja/core_javascript_1.5_reference/global_objects/string/localecompare")
     (item "ja/core_javascript_1.5_reference/global_objects/string/match")
     (item "ja/core_javascript_1.5_reference/global_objects/string/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/string/quote")
     (item "ja/core_javascript_1.5_reference/global_objects/string/replace")
     (item "ja/core_javascript_1.5_reference/global_objects/string/search")
     (item "ja/core_javascript_1.5_reference/global_objects/string/slice")
     (item "ja/core_javascript_1.5_reference/global_objects/string/small")
     (item "ja/core_javascript_1.5_reference/global_objects/string/split")
     (item "ja/core_javascript_1.5_reference/global_objects/string/strike")
     (item "ja/core_javascript_1.5_reference/global_objects/string/sub")
     (item "ja/core_javascript_1.5_reference/global_objects/string/substr")
     (item "ja/core_javascript_1.5_reference/global_objects/string/substring")
     (item "ja/core_javascript_1.5_reference/global_objects/string/sup")
     (item "ja/core_javascript_1.5_reference/global_objects/string/tolocalelowercase")
     (item "ja/core_javascript_1.5_reference/global_objects/string/tolocaleuppercase")
     (item "ja/core_javascript_1.5_reference/global_objects/string/tolowercase")
     (item "ja/core_javascript_1.5_reference/global_objects/string/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/string/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/string/touppercase")
     (item "ja/core_javascript_1.5_reference/global_objects/string/trim")
     (item "ja/core_javascript_1.5_reference/global_objects/string/trimleft")
     (item "ja/core_javascript_1.5_reference/global_objects/string/trimright")
     (item "ja/core_javascript_1.5_reference/global_objects/string/valueof")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/sun")
    (item "ja/core_javascript_1.5_reference/global_objects/syntaxerror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/syntaxerror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/syntaxerror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/syntaxerror/prototype")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/typeerror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/typeerror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/typeerror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/typeerror/prototype")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/urierror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/urierror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/urierror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/urierror/prototype")
     ))
   (item "ja/core_javascript_1.5_reference/global_properties")
   (subsection
    (item "ja/core_javascript_1.5_reference/global_properties/infinity")
    (item "ja/core_javascript_1.5_reference/global_properties/nan")
    (item "ja/core_javascript_1.5_reference/global_properties/undefined")
    )
   (item "ja/core_javascript_1.5_reference/liveconnect")
   (subsection
    (item "ja/core_javascript_1.5_reference/liveconnect/jsexception")
    (item "ja/core_javascript_1.5_reference/liveconnect/jsobject")
    )
   (item "ja/core_javascript_1.5_reference/objects")
   (subsection
    (item "ja/core_javascript_1.5_reference/objects/array")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/objects/array/reduce")
     (item "ja/core_javascript_1.5_reference/objects/array/reduceright")
     )
    (item "ja/core_javascript_1.5_reference/objects/number")
    )
   (item "ja/core_javascript_1.5_reference/operators")
   (subsection
    (item "ja/core_javascript_1.5_reference/operators/arithmetic_operators")
    (item "ja/core_javascript_1.5_reference/operators/assignment_operators")
    (item "ja/core_javascript_1.5_reference/operators/bitwise_operators")
    (item "ja/core_javascript_1.5_reference/operators/comparison_operators")
    (item "ja/core_javascript_1.5_reference/operators/logical_operators")
    (item "ja/core_javascript_1.5_reference/operators/member_operators")
    (item "ja/core_javascript_1.5_reference/operators/operator_precedence")
    (item "ja/core_javascript_1.5_reference/operators/special_operators")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/operators/special_operators/comma_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/conditional_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/delete_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/function_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/get_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/in_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/instanceof_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/new_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/set_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/this_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/typeof_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/void_operator")
     )
    (item "ja/core_javascript_1.5_reference/operators/string_operators")
    )
   (item "ja/core_javascript_1.5_reference/reserved_words")
   (item "ja/core_javascript_1.5_reference/statements")
   (subsection
    (item "ja/core_javascript_1.5_reference/statements/block")
    (item "ja/core_javascript_1.5_reference/statements/break")
    (item "ja/core_javascript_1.5_reference/statements/const")
    (item "ja/core_javascript_1.5_reference/statements/continue")
    (item "ja/core_javascript_1.5_reference/statements/do...while")
    (item "ja/core_javascript_1.5_reference/statements/export")
    (item "ja/core_javascript_1.5_reference/statements/for...in")
    (item "ja/core_javascript_1.5_reference/statements/for")
    (item "ja/core_javascript_1.5_reference/statements/for_each...in")
    (item "ja/core_javascript_1.5_reference/statements/function")
    (item "ja/core_javascript_1.5_reference/statements/if...else")
    (item "ja/core_javascript_1.5_reference/statements/import")
    (item "ja/core_javascript_1.5_reference/statements/label")
    (item "ja/core_javascript_1.5_reference/statements/let")
    (item "ja/core_javascript_1.5_reference/statements/return")
    (item "ja/core_javascript_1.5_reference/statements/switch")
    (item "ja/core_javascript_1.5_reference/statements/throw")
    (item "ja/core_javascript_1.5_reference/statements/try...catch")
    (item "ja/core_javascript_1.5_reference/statements/var")
    (item "ja/core_javascript_1.5_reference/statements/while")
    (item "ja/core_javascript_1.5_reference/statements/with")
    )
   (item "ja/core_javascript_1.5_reference/symbols")
   (subsection
    (item "ja/core_javascript_1.5_reference/symbols/page_title")
    )
   )
  (item "ja/core_javascript_1.5_reference%2f%2freorg")
  )
 )