(use file.util)
(use gauche.parseopt)

(define ht (make-hash-table 'string=?))

(define (main args)
  (let-args (cdr args)
      ((add "a")
       . restargs)
    (for-each (lambda (line)
                (rxmatch-if (#/`([^']+)/ line)
                    (#f out)
                    (hash-table-put! ht out #t)
                    #f))
              (file->string-list (car restargs)))
    (for-each (lambda (key)
                (if add
                  (print " (\"" key "\" .\n  \"" key "\")")
                  (print " (\"" key "\" .\n  #f)")))
              (sort (hash-table-keys ht))))
  0)
