(use file.util)

(define ht (make-hash-table 'string=?))

(define (main args)
  (for-each (lambda (line)
                   (rxmatch-if (#/`([^']+)/ line)
                       (#f out)
                       (hash-table-put! ht out #t)
                       #f))
            (file->string-list (cadr args)))
  (for-each (lambda (key)
              (print " (\"" key "\" .\n  \"" key "\")"))
            (sort (hash-table-keys ht)))
  0)
