\input texinfo  @c -*-texinfo-*-
@comment %**start of header
@setfilename localmdc.info
@settitle Local Mozilla Developer Center
@documentencoding utf-8

@comment %**end of header

@iftex
@finalout
@parskip 4pt plus 1pt
@end iftex

@dircategory Mozilla
@direntry
* MDC: (localmdc). Local Mozilla Developer Center.
@end direntry

@titlepage
@title Local Mozilla Developer Center
@subtitle version 1.0
@author Mozilla Developer Center (http://developer.mozilla.org/)

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2010 Mozilla Developer Center (http://developer.mozilla.org/)
@end titlepage

@ifnottex
@node Top, , (dir), (dir)
@top Local Mozilla Developer Center
@end ifnottex

@menu
* ja/a_basic_raycaster ::
* ja/a_brief_guide_to_mozilla_preferences ::
* ja/a_re-introduction_to_javascript ::
* ja/a_storage_example_in_xul_using_sql_select_and_an_xul_grid ::
* ja/a_xul_bestiary ::
* ja/about ::
* ja/about_javascript ::
* ja/about_nspr ::
* ja/about_the_document_object_model ::
* ja/about_woff ::
* ja/accessibile_dhtml ::
* ja/accessibility ::
* ja/accessibility%2f%2fat-spi_support ::
* ja/accessibility%2f%2fliveregiondevguide ::
* ja/accessibility%2f%2fxul_accessibility_reference ::
* ja/accessibility_faq ::
* ja/accessing_the_windows_registry_using_xpcom ::
* ja/accessing_web_services_in_mozilla_using_wsdl_proxying ::
* ja/activex_control_for_hosting_netscape_plug-ins_in_ie ::
* ja/adapting_xul_applications_for_firefox_1_5 ::
* ja/add_ajax_tests_to_mozilla ::
* ja/adding_a_new_style_property ::
* ja/adding_extensions_using_the_windows_registry ::
* ja/adding_feed_readers_to_firefox ::
* ja/adding_files_to_the_build ::
* ja/adding_phishing_protection_data_providers ::
* ja/adding_preferences_to_an_extension ::
* ja/adding_search_engines_from_web_pages ::
* ja/adding_xpcom_components_to_mozilla_build_system ::
* ja/addons-tab ::
* ja/addons_mozilla_org_(amo)_api_developers__guide ::
* ja/address_book_examples ::
* ja/address_book_interfaces ::
* ja/advancing_javascript_with_libraries_(presentation) ::
* ja/aggregating_the_in-memory_datasource ::
* ja/ajax ::
* ja/ajax_patterns ::
* ja/already_addrefed ::
* ja/alsa ::
* ja/alternative_style ::
* ja/alternative_style_sheets ::
* ja/an_interview_with_douglas_bowman_of_wired_news ::
* ja/an_introduction_to_hacking_mozilla ::
* ja/animated_png_graphics ::
* ja/ant_script_to_assemble_an_extension ::
* ja/api_change_rules ::
* ja/application%2f%2fhttp-index-format_specification ::
* ja/applications-tab ::
* ja/applying_svg_effects_to_html_content ::
* ja/aria ::
* ja/aria_screen_reader_implementors_guide ::
* ja/aria_user_agent_implementors_guide ::
* ja/atlbase_h ::
* ja/autodial_for_windows_nt ::
* ja/autoexpforvc8 ::
* ja/autohide ::
* ja/automated_testing_tips_and_tricks ::
* ja/automatic_mozilla_configurator ::
* ja/automatically_handle_failed_asserts_in_debug_builds ::
* ja/background-position_keyword_order ::
* ja/basic_introduction_to_using_color_management ::
* ja/binary_compatibility ::
* ja/bird_s_eye_view_of_the_mozilla_framework ::
* ja/blackconnect ::
* ja/blackwood ::
* ja/block_and_line_layout_cheat_sheet ::
* ja/bml ::
* ja/bonsai ::
* ja/bookmark_keywords ::
* ja/bootstrapping_a_new_locale ::
* ja/browser_chrome_tests ::
* ja/browser_detection_and_cross_browser_support ::
* ja/browser_feature_detection ::
* ja/bug_writing_guidelines ::
* ja/bugzilla-ja ::
* ja/bugzilla-jp ::
* ja/bugzilla ::
* ja/build ::
* ja/build_and_install ::
* ja/build_static_libs ::
* ja/building_a_component_dll ::
* ja/building_a_mozilla_distribution ::
* ja/building_a_seamonkey_package ::
* ja/building_a_theme ::
* ja/building_accessible_custom_components_in_xul ::
* ja/building_an_extension ::
* ja/building_firefox_with_debug_symbols ::
* ja/building_mozilla ::
* ja/building_mozilla_with_svg_support ::
* ja/building_necko_standalone ::
* ja/building_on_fedora_core_5 ::
* ja/building_on_windows_with_sfu_(interix) ::
* ja/building_pyxpcom ::
* ja/building_transformiix_standalone ::
* ja/building_with_profile-guided_optimization ::
* ja/building_with_static_checking ::
* ja/building_with_vc8_express ::
* ja/building_xulrunner_with_python ::
* ja/building_xxx_standalone ::
* ja/bundles ::
* ja/bundling_multiple_binary_components ::
* ja/bypassing_security_restrictions_and_signing_code ::
* ja/calendar ::
* ja/calicalendarview ::
* ja/calicalendarviewcontroller ::
* ja/califiletype ::
* ja/callgraph ::
* ja/canvas ::
* ja/canvas_tutorial ::
* ja/case_sensitivity_in_class_and_id_names ::
* ja/cert_override_txt ::
* ja/changing_the_priority_of_http_requests ::
* ja/character_sets_supported_by_gecko ::
* ja/checkmayload ::
* ja/checkout_and_build_nspr ::
* ja/choosing_standards_compliance_over_proprietary_practices ::
* ja/choosing_the_right_memory_allocator ::
* ja/chrome ::
* ja/chrome_registration ::
* ja/chrome_tests ::
* ja/code_review_faq ::
* ja/code_snippets ::
* ja/comm-central ::
* ja/command_line_options ::
* ja/common_css_questions ::
* ja/common_pitfalls ::
* ja/communication_between_html_and_your_extension ::
* ja/compare-locales ::
* ja/compiled-code_automated_tests ::
* ja/compiling_32-bit_firefox_on_a_linux_64-bit_os ::
* ja/compiling_mozilla_with_mingw ::
* ja/compiling_the_npruntime_sample_plugin_in_visual_studio ::
* ja/components_classes ::
* ja/components_classesbyid ::
* ja/components_constructor ::
* ja/components_exception ::
* ja/components ::
* ja/components_id ::
* ja/components_interfaces ::
* ja/components_interfacesbyid ::
* ja/components_issuccesscode ::
* ja/components_lastresult ::
* ja/components_manager ::
* ja/components_results ::
* ja/components_returncode ::
* ja/components_stack ::
* ja/components_utils_evalinsandbox ::
* ja/components_utils_forcegc ::
* ja/components_utils_getweakreference ::
* ja/components_utils ::
* ja/components_utils_import ::
* ja/components_utils_reporterror ::
* ja/components_utils_sandbox ::
* ja/components_object ::
* ja/concat ::
* ja/configure_in ::
* ja/configuring_build_options ::
* ja/configuring_servers_for_ogg_media ::
* ja/confirming_unconfirmed_bugs ::
* ja/consistent_list_indentation ::
* ja/console_service ::
* ja/constructor ::
* ja/content_negotiation ::
* ja/content_states_and_the_style_system ::
* ja/controlling_dns_prefetching ::
* ja/controlling_spell_checking_in_html_forms ::
* ja/cookies_in_mozilla ::
* ja/cookies_preferences_in_mozilla ::
* ja/core_javascript_1_5_guide ::
* ja/core_javascript_1_5_reference ::
* ja/core_javascript_1_5_reference%2f%2freorg ::
* ja/correct_object_oriented_programming_for_javascript_(external) ::
* ja/correctly_using_titles_with_external_stylesheets ::
* ja/cppsrcs ::
* ja/crash_reporting ::
* ja/create_a_new_localization ::
* ja/creating_a_cookie_log ::
* ja/creating_a_dynamic_status_bar_extension ::
* ja/creating_a_firefox_sidebar ::
* ja/creating_a_hybrid_cd ::
* ja/creating_a_language_pack ::
* ja/creating_a_localized_windows_installer_of_seamonkey ::
* ja/creating_a_login_manager_storage_module ::
* ja/creating_a_microsummary ::
* ja/creating_a_mozilla_extension ::
* ja/creating_a_patch ::
* ja/creating_a_python_xpcom_component ::
* ja/creating_a_release_tag ::
* ja/creating_a_skin_for_firefox ::
* ja/creating_a_skin_for_firefox%2f%2fgetting_started ::
* ja/creating_a_skin_for_mozilla ::
* ja/creating_a_skin_for_seamonkey_2_x ::
* ja/creating_a_status_bar_extension ::
* ja/creating_custom_events_that_can_pass_data ::
* ja/creating_custom_firefox_extensions_with_the_mozilla_build_system ::
* ja/creating_en-x-dude ::
* ja/creating_javascript_callbacks_in_components ::
* ja/creating_mozsearch_plugins ::
* ja/creating_opensearch_plugins_for_firefox ::
* ja/creating_reftest-based_unit_tests ::
* ja/creating_regular_expressions_for_a_microsummary_generator ::
* ja/creating_sandboxed_http_connections ::
* ja/creating_toolbar_buttons ::
* ja/creating_xpcom_components ::
* ja/creating_xpi_installer_modules ::
* ja/creating_xulrunner_apps_with_the_mozilla_build_system ::
* ja/crmf_request_object ::
* ja/cross-compiling_mozilla ::
* ja/cross-site_xmlhttprequest ::
* ja/cross_compile_mozilla_for_mingw32 ::
* ja/css ::
* ja/css-2_quick_reference ::
* ja/css3_columns ::
* ja/css_counters ::
* ja/css_improvements_in_firefox_3 ::
* ja/css_reference ::
* ja/css_support_charts ::
* ja/custom_styles_for_rss ::
* ja/custom_toolbar_button ::
* ja/cvs_tags ::
* ja/cxxflags ::
* ja/data_uris ::
* ja/db_views_(message_lists) ::
* ja/debnews ::
* ja/debugging ::
* ja/debugging_a_hang_on_os_x ::
* ja/debugging_a_minidump ::
* ja/debugging_a_xulrunner_application ::
* ja/debugging_frame_reflow ::
* ja/debugging_javascript ::
* ja/debugging_memory_leaks ::
* ja/debugging_mozilla_on_linux_faq ::
* ja/debugging_mozilla_on_windows_faq ::
* ja/debugging_mozilla_with_gdb ::
* ja/debugging_mozilla_with_valgrind ::
* ja/debugging_on_mac_os_x ::
* ja/debugging_table_reflow ::
* ja/default_preferences ::
* ja/defining_cross-browser_tooltips ::
* ja/dehydra ::
* ja/deleteme_goodgoddekiwikisucks ::
* ja/demos_of_open_web_technologies ::
* ja/deploying_a_plugin_as_an_extension ::
* ja/depth ::
* ja/describing_microformats_in_javascript ::
* ja/detecting_device_orientation ::
* ja/determining_the_dimensions_of_elements ::
* ja/devedge ::
* ja/developer_build ::
* ja/developer_guide ::
* ja/developing_add-ons ::
* ja/developing_mozilla ::
* ja/developing_new_mozilla_features ::
* ja/developing_tests ::
* ja/devnews ::
* ja/dhtml ::
* ja/dhtml_demonstrations_using_dom%2f%2fstyle ::
* ja/dhtml_demonstrations_using_dom ::
* ja/dialogs_in_xulrunner ::
* ja/differential_inheritance_in_javascript ::
* ja/dirs ::
* ja/disabling_interruptible_reflow ::
* ja/displaying_places_information_using_views ::
* ja/displaying_web_content_in_an_extension_without_security_issues ::
* ja/dist ::
* ja/docshell ::
* ja/document_execcommand ::
* ja/document_loading_-_from_load_start_to_finding_a_handler ::
* ja/documentation_for_bidi_mozilla ::
* ja/documentation_hot_links ::
* ja/dom ::
* ja/dom_client_object_cross-reference ::
* ja/dom_events ::
* ja/dom_implementation_and_scriptability ::
* ja/dom_improvements_in_firefox_3 ::
* ja/dom_inspector ::
* ja/dom_inspector_faq ::
* ja/dom_levels ::
* ja/domparser ::
* ja/download_manager_improvements_in_firefox_3 ::
* ja/download_manager_preferences ::
* ja/downloading_json_and_javascript_in_extensions ::
* ja/downloading_nightly_or_trunk_builds ::
* ja/drag_and_drop ::
* ja/drag_and_drop_events ::
* ja/drag_and_drop_example ::
* ja/drag_and_drop_javascript_wrapper ::
* ja/dragdrop ::
* ja/drawing_graphics_with_canvas ::
* ja/drawing_text_using_a_canvas ::
* ja/dtrace ::
* ja/dynamically_modifying_xul-based_user_interface ::
* ja/e4x ::
* ja/e4x_for_templating ::
* ja/e4x_tutorial ::
* ja/eclipse ::
* ja/ecmascript ::
* ja/ecmascript_dontenum_attribute ::
* ja/editor_embedding_guide ::
* ja/embed_manifest_at ::
* ja/embedded_dialog_api ::
* ja/embedding_faq ::
* ja/embedding_mozilla ::
* ja/embedding_necko ::
* ja/embedding_spidermonkey ::
* ja/embedding_the_editor ::
* ja/encodings_for_localization_files ::
* ja/enhanced_extension_installation ::
* ja/environment_variables_affecting_crash_reporting ::
* ja/error_console ::
* ja/eval ::
* ja/example ::
* ja/exception_logging_in_javascript ::
* ja/export_library ::
* ja/exslt ::
* ja/extension_etiquette ::
* ja/extension_frequently_asked_questions ::
* ja/extension_library ::
* ja/extension_packaging ::
* ja/extension_samples ::
* ja/extension_theming_guidelines ::
* ja/extension_versioning__update_and_compatibility ::
* ja/extensions ::
* ja/extensions_support_in_seamonkey_2 ::
* ja/external_cvs_snapshots_in_mozilla-central ::
* ja/extra_dso_ldopts ::
* ja/extra_dso_libs ::
* ja/fc_cancelfunction ::
* ja/fc_closeallsessions ::
* ja/fc_closesession ::
* ja/fc_copyobject ::
* ja/fc_createobject ::
* ja/fc_decrypt ::
* ja/fc_decryptdigestupdate ::
* ja/fc_decryptfinal ::
* ja/fc_decryptinit ::
* ja/fc_decryptupdate ::
* ja/fc_decryptverifyupdate ::
* ja/fc_derivekey ::
* ja/fc_destroyobject ::
* ja/fc_digest ::
* ja/fc_digestencryptupdate ::
* ja/fc_digestfinal ::
* ja/fc_digestinit ::
* ja/fc_digestkey ::
* ja/fc_digestupdate ::
* ja/fc_encrypt ::
* ja/fc_encryptfinal ::
* ja/fc_encryptinit ::
* ja/fc_encryptupdate ::
* ja/fc_finalize ::
* ja/fc_findobjects ::
* ja/fc_findobjectsfinal ::
* ja/fc_findobjectsinit ::
* ja/fc_generatekey ::
* ja/fc_generatekeypair ::
* ja/fc_generaterandom ::
* ja/fc_getattributevalue ::
* ja/fc_getfunctionlist ::
* ja/fc_getfunctionstatus ::
* ja/fc_getinfo ::
* ja/fc_getmechanisminfo ::
* ja/fc_getmechanismlist ::
* ja/fc_getobjectsize ::
* ja/fc_getoperationstate ::
* ja/fc_getsessioninfo ::
* ja/fc_getslotinfo ::
* ja/fc_getslotlist ::
* ja/fc_gettokeninfo ::
* ja/fc_initialize ::
* ja/fc_initpin ::
* ja/fc_inittoken ::
* ja/fc_login ::
* ja/fc_logout ::
* ja/fc_opensession ::
* ja/fc_seedrandom ::
* ja/fc_setattributevalue ::
* ja/fc_setoperationstate ::
* ja/fc_setpin ::
* ja/fc_sign ::
* ja/fc_signencryptupdate ::
* ja/fc_signfinal ::
* ja/fc_signinit ::
* ja/fc_signrecover ::
* ja/fc_signrecoverinit ::
* ja/fc_signupdate ::
* ja/fc_unwrapkey ::
* ja/fc_verify ::
* ja/fc_verifyfinal ::
* ja/fc_verifyinit ::
* ja/fc_verifyrecover ::
* ja/fc_verifyrecoverinit ::
* ja/fc_verifyupdate ::
* ja/fc_waitforslotevent ::
* ja/fc_wrapkey ::
* ja/feed_content_access_api ::
* ja/fighting_junk_mail_with_netscape_7_1 ::
* ja/file_i%2f%2fo ::
* ja/fileguide ::
* ja/findbar_api ::
* ja/firebug_internals ::
* ja/firefox_1_5_for_developers ::
* ja/firefox_2_for_developers ::
* ja/firefox_3_5_for_developers ::
* ja/firefox_3_6_for_developers ::
* ja/firefox_3_for_developers ::
* ja/firefox_addons_developer_guide ::
* ja/firefoxoverlaypoints ::
* ja/fixing_common_validation_problems ::
* ja/fixing_incorrectly_sized_list_item_markers ::
* ja/fixing_table_inheritance_in_quirks_mode ::
* ja/flags ::
* ja/focus_management_in_html ::
* ja/folders ::
* ja/force_rtl ::
* ja/force_shared_lib ::
* ja/force_static_lib ::
* ja/free%2f%2fopen_source_software ::
* ja/frequently_asked_localization_questions ::
* ja/fuel ::
* ja/full_page_zoom ::
* ja/fun_with_xbl_and_xpconnect ::
* ja/function ::
* ja/functions ::
* ja/gecko-specific_dom_events ::
* ja/gecko ::
* ja/gecko_1_9_changes_affecting_websites ::
* ja/gecko_bugathon ::
* ja/gecko_coding_help_wanted ::
* ja/gecko_compatibility_handbook ::
* ja/gecko_documentation_overview ::
* ja/gecko_documentation_primary_index ::
* ja/gecko_dom_reference ::
* ja/gecko_embedding_api_reference ::
* ja/gecko_embedding_basics ::
* ja/gecko_faq ::
* ja/gecko_glossary ::
* ja/gecko_hacking_tutorial ::
* ja/gecko_keypress_event ::
* ja/gecko_plugin_api_reference ::
* ja/gecko_presentations ::
* ja/gecko_s__almost_standards__mode ::
* ja/gecko_sdk ::
* ja/gecko_user_agent_strings ::
* ja/generating_guids ::
* ja/generic_factory ::
* ja/gettext ::
* ja/getting_commit_access_to_mozilla_source_code ::
* ja/getting_started_with_xulrunner ::
* ja/getting_the_page_url_in_npapi_plugin ::
* ja/gfx2 ::
* ja/giving__cursor__a_hand ::
* ja/glossary ::
* ja/google_maps_via_php ::
* ja/gre ::
* ja/gre_registration ::
* ja/guide_to_shorthand_css ::
* ja/hacking_firefox ::
* ja/hacking_mozilla ::
* ja/hacking_mozilla_dom ::
* ja/hacking_with_bonsai ::
* ja/help_viewer ::
* ja/helper_apps_(and_a_bit_of_save_as) ::
* ja/how_comm-central_s_build_system_works ::
* ja/how_mozilla_determines_mime_types ::
* ja/how_mozilla_s_build_system_works ::
* ja/how_to_add_a_build-time_test ::
* ja/how_to_append_wizardpage ::
* ja/how_to_build_a_binary_xpcom_component_using_visual_studio ::
* ja/how_to_build_an_xpcom_component_in_javascript ::
* ja/how_to_check_the_security_state_of_an_xmlhttprequest_over_ssl ::
* ja/how_to_create_a_dom_tree ::
* ja/how_to_create_windows_inno_setup_installer_for_xulrunner_application ::
* ja/how_to_embed_the_javascript_engine ::
* ja/how_to_enable_locale_switching_in_a_xulrunner_application ::
* ja/how_to_get_a_stacktrace_for_a_bug_report ::
* ja/how_to_get_a_stacktrace_with_windbg ::
* ja/how_to_implement_a_custom_xul_query_processor_component ::
* ja/how_to_implement_custom_autocomplete_search_component ::
* ja/how_to_pass_an_xpcom_object_to_a_new_window ::
* ja/how_to_quit_a_xul_application ::
* ja/how_to_turn_off_form_autocompletion ::
* ja/how_to_update_extensions_for_firefox_1_5 ::
* ja/html ::
* ja/html_element_cross_reference ::
* ja/http_access_control ::
* ja/http_caching_faq ::
* ja/http_class_overview ::
* ja/http_delegation ::
* ja/http_logging ::
* ja/http_pipelining_faq ::
* ja/http_transaction_model ::
* ja/httpd_js ::
* ja/icc_color_correction_in_firefox ::
* ja/idl_interface_rules ::
* ja/images__tables__and_mysterious_gaps ::
* ja/imap ::
* ja/imgiloader ::
* ja/implementing_download_resuming ::
* ja/implementing_queryinterface ::
* ja/incorrect_mime_type_for_css_files ::
* ja/incremental_build ::
* ja/indexof ::
* ja/infallible_memory_allocation ::
* ja/install_js ::
* ja/install_manifests ::
* ja/installing_extensions ::
* ja/installing_extensions_and_themes_from_web_pages ::
* ja/installing_headers_using_exports ::
* ja/installing_mercurial ::
* ja/installing_plugins_to_gecko_embedding_browsers_on_windows ::
* ja/installing_pork ::
* ja/integrated_authentication ::
* ja/interfaces ::
* ja/interfaces_moved_in_firefox_3_6 ::
* ja/interfacing_with_the_xpcom_cycle_collector ::
* ja/international_characters_in_xul_javascript ::
* ja/internationalized_domain_names_(idn)_support_in_mozilla_browsers ::
* ja/introducing_content_security_policy ::
* ja/introduction_to_dom_inspector ::
* ja/introduction_to_layout_in_mozilla ::
* ja/introduction_to_network_security_services ::
* ja/introduction_to_object-oriented_javascript ::
* ja/introduction_to_public-key_cryptography ::
* ja/introduction_to_ssl ::
* ja/introduction_to_the_javascript_shell ::
* ja/introduction_to_using_xpath_in_javascript ::
* ja/introduction_to_xpcom_for_the_dom ::
* ja/introduction_to_xul ::
* ja/io_guide%2f%2fdirectory_keys ::
* ja/io_guide ::
* ja/ipcidconnectservice ::
* ja/ipcitransactionservice ::
* ja/ipdl ::
* ja/isp_data ::
* ja/issues_arising_from_arbitrary-element_hover ::
* ja/jar_manifests ::
* ja/jar_packaging ::
* ja/java_in_firefox_extensions ::
* ja/javascript ::
* ja/javascript-dom_prototypes_in_mozilla ::
* ja/javascript_code_modules ::
* ja/javascript_crypto ::
* ja/javascript_language_resources ::
* ja/javascript_methods_index ::
* ja/javascript_modules ::
* ja/javascript_new_testpage ::
* ja/javascript_presentations ::
* ja/javascript_properties_index ::
* ja/javascript_shells ::
* ja/javascript_style_guide ::
* ja/javascript_templates ::
* ja/javascript_tips ::
* ja/javaxpcom ::
* ja/jetpack ::
* ja/jorendorff ::
* ja/js-ctypes ::
* ja/js_compilefile ::
* ja/js_compilescript ::
* ja/js_constructobject ::
* ja/js_defineobject ::
* ja/js_destroycontext ::
* ja/js_destroyruntime ::
* ja/js_evaluatescript ::
* ja/js_getruntime ::
* ja/js_getruntimeprivate ::
* ja/js_hasinstance ::
* ja/js_newcontext ::
* ja/js_newobject ::
* ja/js_newruntime ::
* ja/js_samevalue ::
* ja/js_shutdown ::
* ja/jsapi_reference ::
* ja/jsdbgapi_reference ::
* ja/jsdistackframe ::
* ja/jshydra ::
* ja/json ::
* ja/jspropertyops_defineproperty ::
* ja/jsruntime ::
* ja/jss ::
* ja/key-navigable_custom_dhtml_widgets ::
* ja/l10n_on_mercurial ::
* ja/labs-tab ::
* ja/lastindexof ::
* ja/layout_debugging_and_triaging_tech_talk_(external) ::
* ja/layout_engine_tech_talk_(external) ::
* ja/layout_faq ::
* ja/layout_system_overview ::
* ja/leak_monitor ::
* ja/learn_xpi_installer_scripting_by_example ::
* ja/length ::
* ja/library_name ::
* ja/libxul_library ::
* ja/lightweightthemesfooter ::
* ja/link_prefetching_faq ::
* ja/linux_cheat_sheet_for_mac_and_windows_programmers ::
* ja/linux_compatibility_reference ::
* ja/list_of_former_mozilla-based_applications ::
* ja/list_of_mozilla-based_applications ::
* ja/listening_to_events ::
* ja/listening_to_events_on_all_tabs ::
* ja/litmus_tests ::
* ja/liveconnect ::
* ja/localization ::
* ja/localization_and_plurals ::
* ja/localization_notes ::
* ja/localization_prerequisites ::
* ja/localizing_an_extension ::
* ja/localizing_extension_descriptions ::
* ja/localizing_extension_metadata_on_addons_mozilla_org ::
* ja/localizing_with_koala ::
* ja/localizing_with_narro ::
* ja/localizing_without_a_specialized_tool ::
* ja/mac_os_x_build_prerequisites%2f%2ffink ::
* ja/mac_os_x_universal_binaries ::
* ja/mailbox ::
* ja/mailnews ::
* ja/mailnews_and_mail_code_review_requirements ::
* ja/mailnews_fakeserver ::
* ja/mailnews_filters ::
* ja/mailnews_protocols ::
* ja/mailnews_xpcshell-tests ::
* ja/maintaining_a_localization_(mercurial) ::
* ja/make_your_xulrunner_app_match_the_system_locale ::
* ja/makefile_in ::
* ja/making_sure_your_theme_works_with_rtl_locales ::
* ja/mandelbrot_set_(external) ::
* ja/manipulating_bookmarks_using_places ::
* ja/manipulating_video_using_canvas ::
* ja/mathml ::
* ja/mccoy ::
* ja/mcd ::
* ja/mcd__mission_control_desktop_aka_autoconfig ::
* ja/media_formats_supported_by_the_audio_and_video_elements ::
* ja/media_gallery ::
* ja/mercurial ::
* ja/mercurial%2f%2fdesired_features ::
* ja/mercurial_basics ::
* ja/mercurial_faq ::
* ja/mercurial_queues ::
* ja/message_summary_database ::
* ja/microsummary_topics ::
* ja/microsummary_xml_grammar_reference ::
* ja/midas ::
* ja/migrate_apps_from_internet_explorer_to_mozilla ::
* ja/migrating_from_internal_linkage_to_frozen_linkage ::
* ja/migrating_raw_components_to_add-ons ::
* ja/migration_plan ::
* ja/mmgc ::
* ja/mobile ::
* ja/mobile-tab ::
* ja/mochitest ::
* ja/mochitest_new ::
* ja/modifying_mochitest_ssl_behavior ::
* ja/modularization_techniques ::
* ja/module ::
* ja/monitoring_downloads ::
* ja/monitoring_http_activity ::
* ja/monitoring_plugins ::
* ja/monitoring_wifi_access_points ::
* ja/mork_structure ::
* ja/mork_what_is_it ::
* ja/mork_why ::
* ja/moz_fs_layout ::
* ja/mozijssubscriptloader ::
* ja/mozilla-central ::
* ja/mozilla_dev_apps_firefox-2006-09-29 ::
* ja/mozilla_dev_apps_firefox-2006-10-06 ::
* ja/mozilla_dev_l10n ::
* ja/mozilla_dev_platform_faq ::
* ja/mozilla_application_framework ::
* ja/mozilla_application_framework_in_detail ::
* ja/mozilla_automated_testing ::
* ja/mozilla_build_faq ::
* ja/mozilla_crypto_faq ::
* ja/mozilla_css_support_chart ::
* ja/mozilla_developer_center_contents ::
* ja/mozilla_development_strategies ::
* ja/mozilla_development_tools ::
* ja/mozilla_dom_hacking_guide ::
* ja/mozilla_embedding_apis_overview ::
* ja/mozilla_embedding_faq ::
* ja/mozilla_external_string_guide ::
* ja/mozilla_hacker_s_getting_started_guide ::
* ja/mozilla_internal_string_guide ::
* ja/mozilla_mathml_project ::
* ja/mozilla_modules_and_module_ownership ::
* ja/mozilla_networking_preferences ::
* ja/mozilla_port_blocking ::
* ja/mozilla_project_presentations ::
* ja/mozilla_quirks_mode_behavior ::
* ja/mozilla_release_build_notes ::
* ja/mozilla_release_checklist ::
* ja/mozilla_release_faq ::
* ja/mozilla_s_doctype_sniffing ::
* ja/mozilla_s_quirks_mode ::
* ja/mozilla_source_code_(http ::
* ja/mozilla_source_code_directory_structure ::
* ja/mozilla_style_system ::
* ja/mozilla_style_system_documentation ::
* ja/mozilla_svg_project ::
* ja/mozilla_svg_project_faq ::
* ja/mozilla_svg_status ::
* ja/mozilla_web_developer_community ::
* ja/mozilla_web_developer_faq ::
* ja/mozilla_web_services_security_model ::
* ja/mozilla_webclient ::
* ja/moziregistry ::
* ja/mozistorageaggregatefunction ::
* ja/mozistoragebindingparams ::
* ja/mozistoragebindingparamsarray ::
* ja/mozistorageconnection ::
* ja/mozistorageerror ::
* ja/mozistoragefunction ::
* ja/mozistoragependingstatement ::
* ja/mozistorageprogresshandler ::
* ja/mozistorageresultset ::
* ja/mozistoragerow ::
* ja/mozistorageservice ::
* ja/mozistoragestatement ::
* ja/mozistoragestatementcallback ::
* ja/mozistoragestatementparams ::
* ja/mozistoragestatementrow ::
* ja/mozistoragestatementwrapper ::
* ja/mozistoragevaluearray ::
* ja/mozmill ::
* ja/mozmill_tests ::
* ja/msx_emulator_(jsmsx) ::
* ja/multi-process_architecture ::
* ja/multiple_item_packaging ::
* ja/multithreading_in_necko ::
* ja/my_chrome_oven ::
* ja/myrules_mk ::
* ja/namespaces ::
* ja/nanojit ::
* ja/nanojitmerge ::
* ja/necko ::
* ja/necko_architecture ::
* ja/necko_faq ::
* ja/necko_interfaces_overview ::
* ja/new_in_javascript_1_1 ::
* ja/new_in_javascript_1_2 ::
* ja/new_in_javascript_1_3 ::
* ja/new_in_javascript_1_4 ::
* ja/new_in_javascript_1_5 ::
* ja/new_in_javascript_1_6 ::
* ja/new_in_javascript_1_7 ::
* ja/new_in_javascript_1_8_1 ::
* ja/new_in_javascript_1_8 ::
* ja/new_in_javascript_1_9 ::
* ja/new_in_rhino_1_6r6 ::
* ja/new_in_rhino_1_6r7 ::
* ja/new_in_rhino_1_7r1 ::
* ja/new_in_rhino_1_7r2 ::
* ja/new_in_rhino_1_7r3 ::
* ja/new_security_model_for_web_services ::
* ja/nntp ::
* ja/no_proxy_for_configuration ::
* ja/nonblocking_io_in_nspr ::
* ja/notable_bugs_fixed_in_firefox_3 ::
* ja/notes_on_html_reflow ::
* ja/notes_on_tls_-_ssl_3_0_intolerant_servers ::
* ja/np_getmimedescription ::
* ja/np_getvalue ::
* ja/np_initialize ::
* ja/np_port ::
* ja/np_rect ::
* ja/np_region ::
* ja/np_shutdown ::
* ja/npanycallbackstruct ::
* ja/npapi ::
* ja/npbyterange ::
* ja/npclass ::
* ja/npembedprint ::
* ja/npevent ::
* ja/npfullprint ::
* ja/npidentifier ::
* ja/npn_createobject ::
* ja/npn_destroystream ::
* ja/npn_enumerate ::
* ja/npn_evaluate ::
* ja/npn_forceredraw ::
* ja/npn_getauthenticationinfo ::
* ja/npn_getintidentifier ::
* ja/npn_getproperty ::
* ja/npn_getstringidentifier ::
* ja/npn_getstringidentifiers ::
* ja/npn_geturl ::
* ja/npn_geturlnotify ::
* ja/npn_getvalue ::
* ja/npn_getvalueforurl ::
* ja/npn_hasmethod ::
* ja/npn_hasproperty ::
* ja/npn_identifierisstring ::
* ja/npn_intfromidentifier ::
* ja/npn_invalidaterect ::
* ja/npn_invalidateregion ::
* ja/npn_invoke ::
* ja/npn_invokedefault ::
* ja/npn_memalloc ::
* ja/npn_memflush ::
* ja/npn_memfree ::
* ja/npn_newstream ::
* ja/npn_pluginthreadasynccall ::
* ja/npn_posturl ::
* ja/npn_posturlnotify ::
* ja/npn_releaseobject ::
* ja/npn_releasevariantvalue ::
* ja/npn_reloadplugins ::
* ja/npn_removeproperty ::
* ja/npn_requestread ::
* ja/npn_retainobject ::
* ja/npn_setexception ::
* ja/npn_setproperty ::
* ja/npn_setvalue ::
* ja/npn_setvalueforurl ::
* ja/npn_status ::
* ja/npn_useragent ::
* ja/npn_utf8fromidentifier ::
* ja/npn_version ::
* ja/npn_write ::
* ja/npnvariable ::
* ja/npobject ::
* ja/npp ::
* ja/npp_destroy ::
* ja/npp_destroystream ::
* ja/npp_getvalue ::
* ja/npp_handleevent ::
* ja/npp_new ::
* ja/npp_newstream ::
* ja/npp_print ::
* ja/npp_setvalue ::
* ja/npp_setwindow ::
* ja/npp_streamasfile ::
* ja/npp_urlnotify ::
* ja/npp_write ::
* ja/npp_writeready ::
* ja/npprint ::
* ja/npprintcallbackstruct ::
* ja/nppvariable ::
* ja/nprect ::
* ja/npregion ::
* ja/npsaveddata ::
* ja/npsetwindowcallbackstruct ::
* ja/npstream ::
* ja/npstring ::
* ja/nputf8 ::
* ja/npvariant ::
* ja/npvarianttype ::
* ja/npwindow ::
* ja/ns_abort_if_false ::
* ja/ns_addref ::
* ja/ns_alloc ::
* ja/ns_assertion ::
* ja/ns_convertasciitoutf16 ::
* ja/ns_convertasciitoutf16_external ::
* ja/ns_convertutf16toutf8 ::
* ja/ns_convertutf16toutf8_external ::
* ja/ns_convertutf8toutf16 ::
* ja/ns_convertutf8toutf16_external ::
* ja/ns_cstringappenddata ::
* ja/ns_cstringclonedata ::
* ja/ns_cstringcontainerfinish ::
* ja/ns_cstringcontainerinit ::
* ja/ns_cstringcontainerinit2 ::
* ja/ns_cstringcopy ::
* ja/ns_cstringcutdata ::
* ja/ns_cstringgetdata ::
* ja/ns_cstringgetmutabledata ::
* ja/ns_cstringinsertdata ::
* ja/ns_cstringsetdata ::
* ja/ns_cstringsetdatarange ::
* ja/ns_cstringtoutf16 ::
* ja/ns_ensure_arg_pointer ::
* ja/ns_ensure_success ::
* ja/ns_ensure_true ::
* ja/ns_error ::
* ja/ns_free ::
* ja/ns_getcomponentmanager ::
* ja/ns_getcomponentregistrar ::
* ja/ns_getmemorymanager ::
* ja/ns_getservicemanager ::
* ja/ns_if_addref ::
* ja/ns_if_release ::
* ja/ns_initxpcom2 ::
* ja/ns_initxpcom3 ::
* ja/ns_lossyconvertutf16toascii ::
* ja/ns_lossyconvertutf16toascii_external ::
* ja/ns_newlocalfile ::
* ja/ns_newnativelocalfile ::
* ja/ns_override ::
* ja/ns_postcondition ::
* ja/ns_precondition ::
* ja/ns_realloc ::
* ja/ns_release ::
* ja/ns_shutdownxpcom ::
* ja/ns_stringappenddata ::
* ja/ns_stringclonedata ::
* ja/ns_stringcontainerfinish ::
* ja/ns_stringcontainerinit ::
* ja/ns_stringcopy ::
* ja/ns_stringcutdata ::
* ja/ns_stringgetdata ::
* ja/ns_stringinsertdata ::
* ja/ns_stringsetdata ::
* ja/ns_stringsetdatarange ::
* ja/ns_utf16tocstring ::
* ja/ns_warning ::
* ja/nsacstring ::
* ja/nsacstring_(external) ::
* ja/nsacstring_internal ::
* ja/nsadoptingcstring ::
* ja/nsadoptingstring ::
* ja/nsastring ::
* ja/nsastring_(external) ::
* ja/nsastring_internal ::
* ja/nsautoref ::
* ja/nsautoreftraits ::
* ja/nsautostring ::
* ja/nsautostring_(external) ::
* ja/nsc_inittoken ::
* ja/nsc_login ::
* ja/nsc_setpin ::
* ja/nscategorymanager ::
* ja/nscautostring ::
* ja/nscautostring_(external) ::
* ja/nscomptr ::
* ja/nscountedref ::
* ja/nscstring ::
* ja/nscstring_external ::
* ja/nscstringcontainer_(external) ::
* ja/nscstringencoding ::
* ja/nsdependentcstring ::
* ja/nsdependentcstring_external ::
* ja/nsdependentcsubstring ::
* ja/nsdependentcsubstring_external ::
* ja/nsdependentstring ::
* ja/nsdependentstring_external ::
* ja/nsdependentsubstring ::
* ja/nsdependentsubstring_external ::
* ja/nsdirectoryservice ::
* ja/nsdistmode ::
* ja/nsembedcstring ::
* ja/nsembedstring ::
* ja/nsfixedcstring ::
* ja/nsfixedstring ::
* ja/nsgetmoduleproc ::
* ja/nsiabcard%2f%2fthunderbird3 ::
* ja/nsiabcard ::
* ja/nsiacceleration ::
* ja/nsiaccelerationlistener ::
* ja/nsiaccelerometer ::
* ja/nsiaccessible ::
* ja/nsiaccessibledocument ::
* ja/nsiaccessiblehyperlink ::
* ja/nsiaccessiblehypertext ::
* ja/nsiaccessibleprovider ::
* ja/nsiannotationobserver ::
* ja/nsiannotationservice ::
* ja/nsiboxobject ::
* ja/nsibrowserhistory ::
* ja/nsicacheentrydescriptor ::
* ja/nsicancelable ::
* ja/nsichannel ::
* ja/nsiclassinfo ::
* ja/nsiclipboard ::
* ja/nsiclipboardhelper ::
* ja/nsiconsoleservice ::
* ja/nsicontentpolicy ::
* ja/nsicontentprefobserver ::
* ja/nsicontentprefservice ::
* ja/nsicookie ::
* ja/nsicookie2 ::
* ja/nsicookie2_mozilla_1_8_branch ::
* ja/nsicookiemanager ::
* ja/nsicookiemanager2 ::
* ja/nsicookiepermission ::
* ja/nsicookiepromptservice ::
* ja/nsicookiestorage ::
* ja/nsicryptohash ::
* ja/nsidirectoryservice ::
* ja/nsidirindexlistener ::
* ja/nsidnsservice ::
* ja/nsidomchromewindow ::
* ja/nsidomclientrect ::
* ja/nsidomeventlistener ::
* ja/nsidomfile ::
* ja/nsidomfileerror ::
* ja/nsidomfileexception ::
* ja/nsidomfilelist ::
* ja/nsidomfilereader ::
* ja/nsidomgeopositionaddress ::
* ja/nsidomhtmlmediaelement ::
* ja/nsidommousescrollevent ::
* ja/nsidomofflineresourcelist ::
* ja/nsidomsimplegestureevent ::
* ja/nsidomstorage ::
* ja/nsidomstorage2 ::
* ja/nsidomstorageevent ::
* ja/nsidomstoragelist ::
* ja/nsidomstoragewindow ::
* ja/nsidomwindow ::
* ja/nsidownload ::
* ja/nsidownloadmanager ::
* ja/nsidownloadmanagerui ::
* ja/nsidownloadprogresslistener ::
* ja/nsidragservice ::
* ja/nsidynamiccontainer ::
* ja/nsieffectivetldservice ::
* ja/nsiexternalprotocolservice ::
* ja/nsifaviconservice ::
* ja/nsifeed ::
* ja/nsifeedcontainer ::
* ja/nsifeedelementbase ::
* ja/nsifeedentry ::
* ja/nsifeedgenerator ::
* ja/nsifeedperson ::
* ja/nsifeedprocessor ::
* ja/nsifeedprogresslistener ::
* ja/nsifeedresult ::
* ja/nsifeedresultlistener ::
* ja/nsifeedtextconstruct ::
* ja/nsifileinputstream ::
* ja/nsifileoutputstream ::
* ja/nsiglobalhistory2 ::
* ja/nsiglobalhistory3 ::
* ja/nsihttpactivitydistributor ::
* ja/nsihttpactivityobserver ::
* ja/nsihttpheadervisitor ::
* ja/nsiidleservice ::
* ja/nsiinputstream ::
* ja/nsijscid ::
* ja/nsijson ::
* ja/nsijsxmlhttprequest ::
* ja/nsilivemarkservice ::
* ja/nsilocalfile ::
* ja/nsilogininfo ::
* ja/nsiloginmanager ::
* ja/nsimicrosummaryobserver ::
* ja/nsimsgprotocolinfo ::
* ja/nsimsgsearchsession ::
* ja/nsinavbookmarkobserver ::
* ja/nsinavbookmarksservice ::
* ja/nsinavhistorycontainerresultnode ::
* ja/nsinavhistoryfullvisitresultnode ::
* ja/nsinavhistoryobserver ::
* ja/nsinavhistoryquery ::
* ja/nsinavhistoryqueryoptions ::
* ja/nsinavhistoryqueryresultnode ::
* ja/nsinavhistoryresult ::
* ja/nsinavhistoryresultnode ::
* ja/nsinavhistoryresulttreeviewer ::
* ja/nsinavhistoryresultviewer ::
* ja/nsinavhistoryresultviewobserver ::
* ja/nsinavhistoryservice ::
* ja/nsinavhistoryvisitresultnode ::
* ja/nsiobserver ::
* ja/nsiobserverservice ::
* ja/nsioutputstream ::
* ja/nsipassword ::
* ja/nsipasswordmanager ::
* ja/nsiplacesview ::
* ja/nsiprefbranch ::
* ja/nsiprivatebrowsingservice ::
* ja/nsiprogramminglanguage ::
* ja/nsipromptservice ::
* ja/nsipropertybag ::
* ja/nsipropertybag2 ::
* ja/nsiprotocolproxycallback ::
* ja/nsiprotocolproxyfilter ::
* ja/nsiprotocolproxyservice ::
* ja/nsiproxyinfo ::
* ja/nsiscriptableinputstream ::
* ja/nsiscriptableunescapehtml ::
* ja/nsiscriptableunicodeconverter ::
* ja/nsiscripterror ::
* ja/nsisessionstore ::
* ja/nsisimpleenumerator ::
* ja/nsisockettransportservice ::
* ja/nsisslerrorlistener ::
* ja/nsistringbundle ::
* ja/nsisupports ::
* ja/nsisupports_proxies ::
* ja/nsisupportscstring ::
* ja/nsisupportspriority ::
* ja/nsitaggingservice ::
* ja/nsitaskbarpreview ::
* ja/nsitaskbarpreviewbutton ::
* ja/nsitaskbarpreviewcontroller ::
* ja/nsitaskbartabpreview ::
* ja/nsitaskbarwindowpreview ::
* ja/nsithread ::
* ja/nsithreadeventfilter ::
* ja/nsithreadinternal ::
* ja/nsithreadmanager ::
* ja/nsithreadobserver ::
* ja/nsithreadpool ::
* ja/nsitimer ::
* ja/nsiwebprogress ::
* ja/nsiwebprogresslistener ::
* ja/nsiwifiaccesspoint ::
* ja/nsiwifilistener ::
* ja/nsiwifimonitor ::
* ja/nsiwindowmediator ::
* ja/nsiwintaskbar ::
* ja/nsiwritablepropertybag2 ::
* ja/nsixmlhttprequest ::
* ja/nsixpcexception ::
* ja/nsixsltprocessorobsolete ::
* ja/nsixulappinfo ::
* ja/nsizipentry ::
* ja/nsizipreader ::
* ja/nsizipwriter ::
* ja/nsliteralcstring_(external) ::
* ja/nsliteralstring_(external) ::
* ja/nslocalfile ::
* ja/nsmemory ::
* ja/nsmsgnavigationtype ::
* ja/nsmsgviewcommandcheckstate ::
* ja/nsmsgviewcommandtype ::
* ja/nsmsgviewflagstype ::
* ja/nsmsgviewsortorder ::
* ja/nsmsgviewsorttype ::
* ja/nsmsgviewtype ::
* ja/nsobserverservice ::
* ja/nspipromptservice ::
* ja/nspr ::
* ja/nspr_api_reference ::
* ja/nspr_build_instructions ::
* ja/nspr_contributor_guide ::
* ja/nspr_poll_method ::
* ja/nspr_release_engineering_guide ::
* ja/nspr_release_procedure ::
* ja/nspr_s_position_on_abrupt_thread_termination ::
* ja/nspromiseflatcstring ::
* ja/nspromiseflatstring ::
* ja/nsrefptr ::
* ja/nss ::
* ja/nss_certificate_download_specification ::
* ja/nss_certificate_functions ::
* ja/nss_certverify_log ::
* ja/nss_code_coverage ::
* ja/nss_faq ::
* ja/nss_functions ::
* ja/nss_initialize ::
* ja/nss_key_functions ::
* ja/nss_key_log_format ::
* ja/nss_memory_allocation ::
* ja/nss_pkcs11_functions ::
* ja/nss_reference ::
* ja/nsscriptableinputstream ::
* ja/nsstaticmoduleinfo ::
* ja/nsstring ::
* ja/nsstring_external ::
* ja/nsstringcontainer_(external) ::
* ja/nssupportsweakreference ::
* ja/nsxpidlcstring ::
* ja/nsxpidlstring ::
* ja/observer_notifications ::
* ja/offering_a_context_menu_for_form_controls ::
* ja/offline_resources_in_firefox ::
* ja/oleacc_idl ::
* ja/online ::
* ja/online_and_offline_events ::
* ja/opening_a_link_in_the_default_browser ::
* ja/optimizing_applications_for_nspr ::
* ja/optimizing_your_pages_for_speculative_parsing ::
* ja/os ::
* ja/os_target ::
* ja/other_javascript_tools ::
* ja/overview_of_how_downloads_work ::
* ja/overview_of_nss ::
* ja/package_filename_convention ::
* ja/parsing_and_serializing_xml ::
* ja/parsing_html_from_chrome ::
* ja/parsing_microformats_in_javascript ::
* ja/participating_in_the_mozilla_project ::
* ja/patching_a_localization ::
* ja/php ::
* ja/pkcs11 ::
* ja/pkcs11_faq ::
* ja/pkcs11_implement ::
* ja/pkcs11_module_installation ::
* ja/pkcs11_module_specs ::
* ja/pl_comparestrings ::
* ja/pl_comparevalues ::
* ja/pl_hashstring ::
* ja/pl_hashtableadd ::
* ja/pl_hashtabledestroy ::
* ja/pl_hashtableenumerateentries ::
* ja/pl_hashtablelookup ::
* ja/pl_hashtableremove ::
* ja/pl_newhashtable ::
* ja/pl_strcpy ::
* ja/pl_strdup ::
* ja/pl_strfree ::
* ja/pl_strlen ::
* ja/places ::
* ja/places_developer_guide ::
* ja/places_expiration ::
* ja/places_migration_guide ::
* ja/places_query_uris ::
* ja/places_utilities_for_javascript ::
* ja/plhashallocops ::
* ja/plhashcomparator ::
* ja/plhashentry ::
* ja/plhashenumerator ::
* ja/plhashfunction ::
* ja/plhashnumber ::
* ja/plhashtable ::
* ja/plugin_architecture ::
* ja/plugins ::
* ja/plxpcom ::
* ja/pop3 ::
* ja/popup_window_controls ::
* ja/pork ::
* ja/pork_tool_development ::
* ja/pork_tools ::
* ja/porting_nspr_to_unix_platforms ::
* ja/pr_abort ::
* ja/pr_accept ::
* ja/pr_acceptread ::
* ja/pr_access ::
* ja/pr_append_link ::
* ja/pr_assert ::
* ja/pr_atomicdecrement ::
* ja/pr_atomicincrement ::
* ja/pr_atomicset ::
* ja/pr_attachsharedmemory ::
* ja/pr_attachthread ::
* ja/pr_available ::
* ja/pr_available64 ::
* ja/pr_bind ::
* ja/pr_blockclockinterrupts ::
* ja/pr_callback ::
* ja/pr_calloc ::
* ja/pr_callonce ::
* ja/pr_canceljob ::
* ja/pr_centermonitor ::
* ja/pr_cexitmonitor ::
* ja/pr_cleanup ::
* ja/pr_clearinterrupt ::
* ja/pr_clist_is_empty ::
* ja/pr_close ::
* ja/pr_closedir ::
* ja/pr_closefilemap ::
* ja/pr_closesemaphore ::
* ja/pr_closesharedmemory ::
* ja/pr_cnotify ::
* ja/pr_cnotifyall ::
* ja/pr_cnvtf ::
* ja/pr_connect ::
* ja/pr_createfilemap ::
* ja/pr_createiolayerstub ::
* ja/pr_createpipe ::
* ja/pr_createthread ::
* ja/pr_createthreadpool ::
* ja/pr_cwait ::
* ja/pr_delete ::
* ja/pr_deletesemaphore ::
* ja/pr_deletesharedmemory ::
* ja/pr_destroycondvar ::
* ja/pr_destroylock ::
* ja/pr_destroymonitor ::
* ja/pr_destroypollableevent ::
* ja/pr_detachsharedmemory ::
* ja/pr_detachthread ::
* ja/pr_disableclockinterrupts ::
* ja/pr_dtoa ::
* ja/pr_entermonitor ::
* ja/pr_enumerateaddrinfo ::
* ja/pr_enumeratehostent ::
* ja/pr_exitmonitor ::
* ja/pr_explodetime ::
* ja/pr_exportfilemapasstring ::
* ja/pr_extern ::
* ja/pr_familyinet ::
* ja/pr_findsymbol ::
* ja/pr_findsymbolandlibrary ::
* ja/pr_free ::
* ja/pr_freeaddrinfo ::
* ja/pr_freeif ::
* ja/pr_freelibraryname ::
* ja/pr_getaddrinfobyname ::
* ja/pr_getcanonnamefromaddrinfo ::
* ja/pr_getconnectstatus ::
* ja/pr_getcurrentthread ::
* ja/pr_getdefaultiomethods ::
* ja/pr_getdesctype ::
* ja/pr_geterror ::
* ja/pr_geterrortext ::
* ja/pr_geterrortextlength ::
* ja/pr_getfileinfo ::
* ja/pr_getfileinfo64 ::
* ja/pr_gethostbyaddr ::
* ja/pr_gethostbyname ::
* ja/pr_getidentitieslayer ::
* ja/pr_getinheritedfilemap ::
* ja/pr_getlayersidentity ::
* ja/pr_getlibraryname ::
* ja/pr_getlibrarypath ::
* ja/pr_getnameforidentity ::
* ja/pr_getopenfileinfo ::
* ja/pr_getopenfileinfo64 ::
* ja/pr_getoserror ::
* ja/pr_getpeername ::
* ja/pr_getprotobyname ::
* ja/pr_getprotobynumber ::
* ja/pr_getrandomnoise ::
* ja/pr_getsocketoption ::
* ja/pr_getsockname ::
* ja/pr_getspecialfd ::
* ja/pr_getthreadpriority ::
* ja/pr_getthreadprivate ::
* ja/pr_getthreadscope ::
* ja/pr_getuniqueidentity ::
* ja/pr_gmtparameters ::
* ja/pr_htonl ::
* ja/pr_htons ::
* ja/pr_implement ::
* ja/pr_implodetime ::
* ja/pr_importfilemapfromstring ::
* ja/pr_importtcpsocket ::
* ja/pr_init ::
* ja/pr_init_clist ::
* ja/pr_init_static_clist ::
* ja/pr_initialize ::
* ja/pr_initialized ::
* ja/pr_initializenetaddr ::
* ja/pr_insert_after ::
* ja/pr_insert_before ::
* ja/pr_insert_link ::
* ja/pr_interrupt ::
* ja/pr_intervalnow ::
* ja/pr_intervaltomicroseconds ::
* ja/pr_intervaltomilliseconds ::
* ja/pr_intervaltoseconds ::
* ja/pr_joinjob ::
* ja/pr_jointhread ::
* ja/pr_jointhreadpool ::
* ja/pr_list_head ::
* ja/pr_list_tail ::
* ja/pr_listen ::
* ja/pr_loadlibrary ::
* ja/pr_localtimeparameters ::
* ja/pr_lock ::
* ja/pr_malloc ::
* ja/pr_memmap ::
* ja/pr_memunmap ::
* ja/pr_microsecondstointerval ::
* ja/pr_millisecondstointerval ::
* ja/pr_mkdir ::
* ja/pr_msec_per_sec ::
* ja/pr_name ::
* ja/pr_netaddrtostring ::
* ja/pr_netdb_buf_size ::
* ja/pr_new ::
* ja/pr_newcondvar ::
* ja/pr_newlock ::
* ja/pr_newmonitor ::
* ja/pr_newpollableevent ::
* ja/pr_newprocessattr ::
* ja/pr_newtcpsocket ::
* ja/pr_newthreadprivateindex ::
* ja/pr_newudpsocket ::
* ja/pr_newzap ::
* ja/pr_next_link ::
* ja/pr_normalizetime ::
* ja/pr_notify ::
* ja/pr_notifyall ::
* ja/pr_notifyallcondvar ::
* ja/pr_notifycondvar ::
* ja/pr_now ::
* ja/pr_nsec_per_msec ::
* ja/pr_nsec_per_sec ::
* ja/pr_ntohl ::
* ja/pr_ntohs ::
* ja/pr_open ::
* ja/pr_openanonfilemap ::
* ja/pr_opendir ::
* ja/pr_opensemaphore ::
* ja/pr_opensharedmemory ::
* ja/pr_opentcpsocket ::
* ja/pr_openudpsocket ::
* ja/pr_poll ::
* ja/pr_popiolayer ::
* ja/pr_postsemaphore ::
* ja/pr_prev_link ::
* ja/pr_processattrsetinheritablefilemap ::
* ja/pr_processexit ::
* ja/pr_pushiolayer ::
* ja/pr_queuejob ::
* ja/pr_queuejob_connect ::
* ja/pr_queuejob_read ::
* ja/pr_queuejob_timer ::
* ja/pr_queuejob_write ::
* ja/pr_queuejobaccept ::
* ja/pr_read ::
* ja/pr_readdir ::
* ja/pr_realloc ::
* ja/pr_recv ::
* ja/pr_recvfrom ::
* ja/pr_remove_and_init_link ::
* ja/pr_remove_link ::
* ja/pr_rename ::
* ja/pr_rmdir ::
* ja/pr_secondstointerval ::
* ja/pr_seek ::
* ja/pr_seek64 ::
* ja/pr_send ::
* ja/pr_sendto ::
* ja/pr_setconcurrency ::
* ja/pr_seterror ::
* ja/pr_seterrortext ::
* ja/pr_setipv6enable ::
* ja/pr_setlibrarypath ::
* ja/pr_setpollableevent ::
* ja/pr_setsocketoption ::
* ja/pr_setthreadpriority ::
* ja/pr_setthreadprivate ::
* ja/pr_shutdown ::
* ja/pr_shutdownthreadpool ::
* ja/pr_sleep ::
* ja/pr_static_assert ::
* ja/pr_stringtonetaddr ::
* ja/pr_strtod ::
* ja/pr_sync ::
* ja/pr_tickspersecond ::
* ja/pr_transmitfile ::
* ja/pr_unblockclockinterrupts ::
* ja/pr_unloadlibrary ::
* ja/pr_unlock ::
* ja/pr_usec_per_msec ::
* ja/pr_usec_per_sec ::
* ja/pr_version ::
* ja/pr_versioncheck ::
* ja/pr_wait ::
* ja/pr_waitcondvar ::
* ja/pr_waitforpollableevent ::
* ja/pr_waitsemaphore ::
* ja/pr_write ::
* ja/pr_writev ::
* ja/praccesshow ::
* ja/prbool ::
* ja/prcalloncefn ::
* ja/prcalloncetype ::
* ja/prclist ::
* ja/prcondvar ::
* ja/prdescidentity ::
* ja/prdir ::
* ja/preferences_api ::
* ja/preferences_system ::
* ja/prerrorcode ::
* ja/prexplodedtime ::
* ja/prfiledesc ::
* ja/prfileinfo ::
* ja/prfileinfo64 ::
* ja/prfilemap ::
* ja/prfileprivate ::
* ja/prfiletype ::
* ja/prfloat64 ::
* ja/prhostent ::
* ja/print16 ::
* ja/print32 ::
* ja/print64 ::
* ja/print8 ::
* ja/printervaltime ::
* ja/printn ::
* ja/priomethods ::
* ja/pripv6addr ::
* ja/prism ::
* ja/prjob ::
* ja/prjobfn ::
* ja/prjobiodesc ::
* ja/prlibrary ::
* ja/prlinger ::
* ja/prlock ::
* ja/prmcastrequest ::
* ja/prmonitor ::
* ja/prnetaddr ::
* ja/process_forking_in_nspr ::
* ja/processing_xml_with_e4x ::
* ja/profiling_javascript_with_shark ::
* ja/profiling_spidermonkey ::
* ja/profiling_with_vtune ::
* ja/profiling_with_xperf ::
* ja/programs_using_nspr ::
* ja/promiseflatcstring_(external) ::
* ja/promiseflatstring_(external) ::
* ja/properly_configuring_server_mime_types ::
* ja/properly_using_css_and_javascript_in_xhtml_documents ::
* ja/prototype ::
* ja/proxies_in_necko ::
* ja/proxy_ui ::
* ja/prpackedbool ::
* ja/prprimordialfn ::
* ja/prprocess ::
* ja/prprocessattr ::
* ja/prprotoent ::
* ja/prptrdiff ::
* ja/prseekwhence ::
* ja/prsize ::
* ja/prsocketoptiondata ::
* ja/prsockoption ::
* ja/prstaticlinktable ::
* ja/prstatus ::
* ja/prthread ::
* ja/prthreadpool ::
* ja/prthreadpriority ::
* ja/prthreadprivatedtor ::
* ja/prthreadscope ::
* ja/prthreadstack ::
* ja/prthreadstate ::
* ja/prthreadtype ::
* ja/prtime ::
* ja/prtimeparameters ::
* ja/prtimeparamfn ::
* ja/pruint16 ::
* ja/pruint32 ::
* ja/pruint64 ::
* ja/pruint8 ::
* ja/pruintn ::
* ja/prunichar ::
* ja/pruptrdiff ::
* ja/publishing_mercurial_clones ::
* ja/pydom ::
* ja/pylons ::
* ja/pymake ::
* ja/python ::
* ja/pyxpcom ::
* ja/qa ::
* ja/querying_places ::
* ja/rbxpcom ::
* ja/rdf ::
* ja/rdf_api ::
* ja/rdf_datasource_how-to ::
* ja/rdf_in_fifty_words_or_less ::
* ja/rdf_in_mozilla_faq ::
* ja/reading_textual_data ::
* ja/reducing_testcases ::
* ja/reference_build_configurations ::
* ja/reftest_opportunities_files ::
* ja/regexp ::
* ja/remediateie ::
* ja/remote_debugging ::
* ja/remote_xul ::
* ja/renaming_with_pork ::
* ja/repackaging_firefox ::
* ja/retrieving_part_of_the_bookmarks_tree ::
* ja/rhino ::
* ja/rhino_documentation ::
* ja/rhino_downloads_archive ::
* ja/rhino_faq ::
* ja/rhino_help ::
* ja/rhino_javascript_compiler ::
* ja/rhino_optimization ::
* ja/rhino_overview ::
* ja/rhino_requirements_and_limitations ::
* ja/rhino_shell ::
* ja/rich-text_editing_in_mozilla ::
* ja/rich_web ::
* ja/role_character ::
* ja/roll_your_own_browser_-_an_embedding_howto ::
* ja/rss ::
* ja/rsyncing_the_cvs_repository ::
* ja/running_automated_tests ::
* ja/running_nspr_tests ::
* ja/running_the_rhino_tests ::
* ja/runtime_directories ::
* ja/safely_accessing_content_dom_from_chrome ::
* ja/safely_loading_uris ::
* ja/same_origin_policy_for_javascript ::
* ja/same_origin_policy_for_xbl ::
* ja/sample ::
* ja/sample__htaccess_file ::
* ja/sandbox ::
* ja/sandbox%2f%2fhere_is_my_page ::
* ja/sandbox%2f%2fsubpage ::
* ja/sandbox2 ::
* ja/sandboxmove ::
* ja/sax ::
* ja/scratchbox ::
* ja/screening_duplicate_bugs ::
* ja/scripting_java ::
* ja/seamonkey ::
* ja/searching_bugzilla ::
* ja/secure_development_guidelines ::
* ja/security ::
* ja/security_and_the_jar_protocol ::
* ja/security_best_practices_in_extensions ::
* ja/security_changes_in_firefox_3_5 ::
* ja/security_check_basics ::
* ja/security_in_firefox_2 ::
* ja/series ::
* ja/server-side_access_control ::
* ja/server-side_javascript ::
* ja/server-side_javascript_(ssjs) ::
* ja/session_store_api ::
* ja/setting_http_request_headers ::
* ja/setting_up_an_update_server ::
* ja/setting_up_extension_development_environment ::
* ja/setting_up_jprof ::
* ja/sharp_variables_in_javascript ::
* ja/shipping_a_plugin_as_a_toolkit_bundle ::
* ja/short_libname ::
* ja/signing_a_xpi ::
* ja/signing_an_executable_with_authenticode ::
* ja/signing_an_extension ::
* ja/sim_daltonism ::
* ja/simple_firefox_build ::
* ja/simple_seamonkey_build ::
* ja/simple_sunbird_build ::
* ja/simple_thunderbird_build ::
* ja/skinning_xul_files_by_hand ::
* ja/slice ::
* ja/smtp ::
* ja/soap_in_gecko-based_browsers ::
* ja/solaris_10_build_prerequisites ::
* ja/sorting_and_filtering_a_custom_tree_view ::
* ja/source_code_directories_overview ::
* ja/source_navigator ::
* ja/space_manager_detailed_design ::
* ja/space_manager_high_level_design ::
* ja/specification ::
* ja/specifications ::
* ja/spidermonkey ::
* ja/spidermonkey_coding_conventions ::
* ja/spidermonkey_garbage_collection_tips ::
* ja/spidermonkey_internals ::
* ja/split ::
* ja/ssjs ::
* ja/standalone_xpcom ::
* ja/standard_makefile_header ::
* ja/standards-compliant_authoring_tools ::
* ja/static_analysis_for_windows_code_under_linux ::
* ja/static_dirs ::
* ja/storage ::
* ja/string_quick_reference ::
* ja/style_system_overview ::
* ja/styling_abbreviations_and_acronyms ::
* ja/styling_the_amazing_netscape_fish_cam_page ::
* ja/submitting_an_add-on_to_amo ::
* ja/sunbird_theme_tutorial ::
* ja/supported_build_configurations ::
* ja/supporting_private_browsing_in_plugins ::
* ja/supporting_private_browsing_mode ::
* ja/supporting_search_suggestions_in_search_plugins ::
* ja/svg ::
* ja/svg%2f%2fproject%2f%2fhelp-out ::
* ja/svg_animation_(smil)_in_firefox ::
* ja/svg_improvements_in_firefox_3 ::
* ja/svg_in_firefox ::
* ja/svg_in_html_introduction ::
* ja/svg_reference ::
* ja/sxsw_2007_presentations ::
* ja/system_headers ::
* ja/table_cellmap ::
* ja/table_cellmap_-_border_collapse ::
* ja/table_layout_regression_tests ::
* ja/table_layout_strategy ::
* ja/table_of_errors ::
* ja/table_reflow_internals ::
* ja/tamarin ::
* ja/tamarin_build_documentation ::
* ja/tamarin_tracing_build_documentation ::
* ja/tempjenzed ::
* ja/templates_in_firefox_3 ::
* ja/test ::
* ja/testing_third-party_pkcs ::
* ja/the_adr_microformat ::
* ja/the_basics_of_web_services ::
* ja/the_business_benefits_of_web_standards ::
* ja/the_dom_and_javascript ::
* ja/the_download_manager_schema ::
* ja/the_geo_microformat ::
* ja/the_hcalendar_microformat ::
* ja/the_hcard_microformat ::
* ja/the_importance_of_correct_html_commenting ::
* ja/the_joy_of_xul ::
* ja/the_life_of_an_html_http_request ::
* ja/the_mozilla_platform ::
* ja/the_necko_http_module ::
* ja/the_new_nsstring_class_implementation_(1999) ::
* ja/the_places_database ::
* ja/the_places_frecency_algorithm ::
* ja/the_tag_microformat ::
* ja/the_thread_manager ::
* ja/the_xslt%2f%2fjavascript_interface_in_gecko ::
* ja/the_xslt ::
* ja/theme_changes_in_firefox_2 ::
* ja/theme_changes_in_firefox_3_5 ::
* ja/theme_changes_in_firefox_3 ::
* ja/theme_packaging ::
* ja/themes ::
* ja/thunderbird ::
* ja/thunderbird_3_for_developers ::
* ja/thunderbird_3_for_users ::
* ja/thunderbird_isp_hooks ::
* ja/tiers ::
* ja/tiersandstuff_> ::
* ja/tinderbox ::
* ja/tips_for_authoring_fast-loading_html_pages ::
* ja/title ::
* ja/tls_cipher_suite_discovery ::
* ja/toolkit_defaultchromefeatures ::
* ja/toolkit_defaultchromeuri ::
* ja/toolkit_singletonwindowtype ::
* ja/toolkit_api ::
* ja/toolkit_version_format ::
* ja/tools ::
* ja/tosource ::
* ja/tostring ::
* ja/tracevis ::
* ja/transforming_xml_with_xslt ::
* ja/traversing_an_html_table_with_javascript_and_dom_interfaces ::
* ja/tree_widget_changes ::
* ja/treehydra ::
* ja/treehydra_build_instructions ::
* ja/treehydra_manual ::
* ja/triaging_crash_bugs ::
* ja/triaging_networking_bugs ::
* ja/troubleshooting_xpcom_components_registration ::
* ja/tuning_pageload ::
* ja/underscores_in_class_and_id_names ::
* ja/understanding_css_z-index ::
* ja/understanding_underlines ::
* ja/unix_detailed_build_instructions ::
* ja/upcoming_firefox_features_for_developers ::
* ja/updating_an_extension_to_support_multiple_mozilla_applications ::
* ja/updating_extensions_for_firefox_2 ::
* ja/updating_extensions_for_firefox_3_1 ::
* ja/updating_extensions_for_firefox_3_5 ::
* ja/updating_extensions_for_firefox_3_6 ::
* ja/updating_extensions_for_firefox_3 ::
* ja/updating_nspr_or_nss_in_mozilla-central ::
* ja/updating_plug-ins_for_firefox_3_6 ::
* ja/updating_themes_for_firefox_3_6 ::
* ja/updating_themes_for_firefox_3 ::
* ja/updating_web_applications_for_firefox_3 ::
* ja/uriloader ::
* ja/uris_and_urls ::
* ja/urischeme ::
* ja/use_extension_manifest ::
* ja/use_static_libs ::
* ja/useful_css_tips ::
* ja/user_agent_strings_reference ::
* ja/using_addresses_of_stack_variables_with_nspr_threads_on_win16 ::
* ja/using_an_external_spell-checker ::
* ja/using_audio_and_video_in_firefox ::
* ja/using_breakpoints_in_venkman ::
* ja/using_content_preferences ::
* ja/using_crash_reporting_in_a_xulrunner_application ::
* ja/using_cross_commit ::
* ja/using_dependent_libraries_in_extension_components ::
* ja/using_files_from_web_applications ::
* ja/using_firebug_and_jquery_(screencast) ::
* ja/using_firefox_1_5_caching ::
* ja/using_gdb_on_wimpy_computers ::
* ja/using_geolocation ::
* ja/using_gradients ::
* ja/using_io_timeout_and_interrupt_on_nt ::
* ja/using_javascript_code_modules ::
* ja/using_microformats ::
* ja/using_mochitests_in_a_xulrunner_application ::
* ja/using_monotone_with_mozilla_cvs ::
* ja/using_mozilla_code_in_other_projects ::
* ja/using_mozilla_in_testing_and_debugging_web_sites ::
* ja/using_multiple_dtds ::
* ja/using_native_json ::
* ja/using_nscomptr ::
* ja/using_nsiclassinfo ::
* ja/using_nsidirectoryservice ::
* ja/using_nsiloginmanager ::
* ja/using_nsipasswordmanager ::
* ja/using_nsisimpleenumerator ::
* ja/using_nsixulappinfo ::
* ja/using_raii_classes_in_mozilla ::
* ja/using_remote_xul ::
* ja/using_soap_in_xulrunner_1_9 ::
* ja/using_spell_checking_in_xul ::
* ja/using_ssh_to_connect_to_cvs ::
* ja/using_svk_with_mozilla_cvs ::
* ja/using_the ::
* ja/using_the_clipboard ::
* ja/using_the_editor_from_xul ::
* ja/using_the_gecko_sdk ::
* ja/using_the_mozilla_javascript_interface_to_xsl_transformations ::
* ja/using_the_mozilla_source_server ::
* ja/using_the_mozilla_symbol_server ::
* ja/using_the_multiple_accounts_api ::
* ja/using_the_places_annotation_service ::
* ja/using_the_places_favicon_service ::
* ja/using_the_places_history_service ::
* ja/using_the_places_livemark_service ::
* ja/using_the_places_tagging_service ::
* ja/using_the_right_markup_to_invoke_plugins ::
* ja/using_the_standard_theme ::
* ja/using_the_stylesheet_service ::
* ja/using_the_w3c_dom_level_1_core ::
* ja/using_url_values_for_the_cursor_property ::
* ja/using_web_standards_in_your_web_pages ::
* ja/using_web_workers ::
* ja/using_workers_in_extensions ::
* ja/using_xml_data_islands_in_mozilla ::
* ja/using_xmlhttprequest ::
* ja/using_xpath ::
* ja/using_xpcom_in_javascript_without_leaking ::
* ja/using_xpinstall_to_install_plugins ::
* ja/vc6_build_instructions ::
* ja/venkman ::
* ja/venkman_internals ::
* ja/venkman_introduction ::
* ja/video_presentations ::
* ja/viewing_and_searching_mozilla_source_code_online ::
* ja/vpath ::
* ja/warnings_as_errors ::
* ja/weak_reference ::
* ja/web-based_protocol_handlers ::
* ja/web-tab ::
* ja/web_1_6 ::
* ja/web_content_accessibility_guidelines_1_0 ::
* ja/web_development ::
* ja/web_localizability ::
* ja/web_standards ::
* ja/webclient_roadmap ::
* ja/webdav ::
* ja/webdav__git__and_hopefully_weave_ ::
* ja/webgl ::
* ja/what_every_mozilla_translator_should_know ::
* ja/what_s_new_in_deer_park_alpha ::
* ja/what_to_do_and_what_not_to_do_in_bugzilla ::
* ja/when_to_use_ifdefs ::
* ja/whitespace_in_the_dom ::
* ja/why_embed_gecko ::
* ja/why_support_mozilla ::
* ja/width ::
* ja/win_big_with_widgets_on_samsung_i8910hd ::
* ja/window_icons ::
* ja/window_terminology ::
* ja/windows_and_menus_in_xulrunner ::
* ja/windows_build_prerequisites_(1_7_and_1_8_branches) ::
* ja/windows_build_prerequisites_on_the_1_7_and_1_8_branches ::
* ja/windows_build_prerequisites_using_cygwin ::
* ja/windows_media_in_netscape ::
* ja/windows_sdk_versions ::
* ja/working_around_the_firefox_1_0_3_dhtml_regression ::
* ja/working_with_bfcache ::
* ja/working_with_chrome_urls ::
* ja/working_with_multiple_versions_of_interfaces ::
* ja/working_with_out_parameters ::
* ja/working_with_windows_in_chrome_code ::
* ja/wpcapi_h ::
* ja/wrappedjsobject ::
* ja/writing_a_plugin_for_mac_os_x ::
* ja/writing_efficient_css ::
* ja/writing_javascript_for_xhtml ::
* ja/writing_localizable_code ::
* ja/writing_skinnable_xul_and_css ::
* ja/writing_textual_data ::
* ja/writing_xpcshell-based_unit_tests ::
* ja/xbdesignmode_js ::
* ja/xbl ::
* ja/xembed_extension_for_mozilla_plugins ::
* ja/xforms ::
* ja/xhtml ::
* ja/xinclude ::
* ja/xlink ::
* ja/xml ::
* ja/xml_extras ::
* ja/xml_in_mozilla ::
* ja/xml_introduction ::
* ja/xml_web_services ::
* ja/xmlhttprequest ::
* ja/xmlhttprequest_changes_for_gecko1_8 ::
* ja/xmlserializer ::
* ja/xpath ::
* ja/xpathexpression ::
* ja/xpathresult ::
* ja/xpcnativewrapper ::
* ja/xpcom ::
* ja/xpcom_abi ::
* ja/xpcom_api_reference ::
* ja/xpcom_array_guide ::
* ja/xpcom_category_image-sniffing-services ::
* ja/xpcom_components_list ::
* ja/xpcom_debug_break ::
* ja/xpcom_glue ::
* ja/xpcom_hashtable_guide ::
* ja/xpcom_interface_reference ::
* ja/xpcom_ownership_guidelines ::
* ja/xpcom_part_1 ::
* ja/xpcom_part_2 ::
* ja/xpcom_part_3 ::
* ja/xpcom_part_4 ::
* ja/xpcom_part_5 ::
* ja/xpcom_plans ::
* ja/xpcom_primitive ::
* ja/xpcom_string_guide ::
* ja/xpcom_tasks ::
* ja/xpcom_thread_synchronization ::
* ja/xpcomutils_jsm ::
* ja/xpconnect ::
* ja/xpconnect_security_membranes ::
* ja/xpconnect_wrappers ::
* ja/xpcshell ::
* ja/xpcshell_reference ::
* ja/xpcshell_tests ::
* ja/xpi ::
* ja/xpidl ::
* ja/xpinstall ::
* ja/xpinstall_api_reference ::
* ja/xpjs_components_proposal ::
* ja/xpshell ::
* ja/xptcall_faq ::
* ja/xptcall_porting_guide ::
* ja/xptcall_porting_status ::
* ja/xquery ::
* ja/xre ::
* ja/xsl_transformations_in_mozilla_faq ::
* ja/xsl_transforms ::
* ja/xslt ::
* ja/xslt_2_0 ::
* ja/xslt_in_gecko ::
* ja/xsltprocessor ::
* ja/xtech_2005_presensations ::
* ja/xtech_2005_presentations ::
* ja/xtech_2006_presentations ::
* ja/xtf ::
* ja/xul ::
* ja/xul%2f%2fattribute%2f%2fresizer_element ::
* ja/xul_accessibility_guidelines ::
* ja/xul_accessibility_tool ::
* ja/xul_accesskey_faq_and_policies ::
* ja/xul_and_rdf ::
* ja/xul_application_packaging ::
* ja/xul_application_tutorial_(external) ::
* ja/xul_booster ::
* ja/xul_changes_for_firefox_1_5 ::
* ja/xul_coding_style_guidelines ::
* ja/xul_controls ::
* ja/xul_element_attributes ::
* ja/xul_event_propagation ::
* ja/xul_explorer ::
* ja/xul_faq ::
* ja/xul_genealogy ::
* ja/xul_improvements_in_firefox_3 ::
* ja/xul_overlays ::
* ja/xul_parser_in_python%2f%2fsource ::
* ja/xul_parser_in_python ::
* ja/xul_questions_and_answers ::
* ja/xul_reference ::
* ja/xul_school ::
* ja/xul_template_primer_-_bindings ::
* ja/xul_template_tag_reference ::
* ja/xul_tutorial ::
* ja/xulauncher ::
* ja/xulplanet ::
* ja/xulref ::
* ja/xulrunner ::
* ja/xulrunner%2f%2fold_releases ::
* ja/xulrunner_1_8_0_1_release_notes ::
* ja/xulrunner_1_8_0_4_release_notes ::
* ja/xulrunner_1_9_1_release_notes ::
* ja/xulrunner_1_9_2_release_notes ::
* ja/xulrunner_1_9_release_notes ::
* ja/xulrunner_faq ::
* ja/xulrunner_hall_of_fame ::
* ja/xulrunner_tips ::
* ja/localmdcindex::
@end menu

@lowersections
@include includes.texi

@node ja/localmdcindex,,,Top
@appendix 索引
@printindex cp
@contents
@bye
