(use srfi-1)
(use srfi-13)
(use file.util)
(use rfc.uri)
(use gauche.parseopt)
(use sxml.ssax)
(use sxml.sxpath)
(use sxml.tools)
(use sxml.tree-trans)
(use sxml.serializer)

(load "common.scm")

(define (a-href-change-lang-from-en-to-ja node)
  (define (f uri)
    (rxmatch-if (#/(.*)\/developer\.mozilla\.org\/en\/(.*)/ uri)
        (#f before after)
        (string-append before "/developer.mozilla.org/ja/" after)
        #f))

  (and-let* ((href (sxml:attr node 'href))
             (href (f (sxml:string-value href))))
    (sxml:change-attr node `(href ,href))))

(define (convert sxml)
  (pre-post-order
   sxml
   `((xhtml:a     . ,(lambda x (or (a-href-change-lang-from-en-to-ja x "en" "ja") x)))
     (*text*      . ,(lambda (tag text) text))
     (*default*   . ,(lambda x x)))))

(define (main args)
  (let-args (cdr args)
      ((verbose "v|verbose")
       . restargs)
    (for-each (lambda (path)
                (and-let* (((file-is-regular? path))
                           (dest-path (change-path path "en" "ja"))
                           ((not (file-exists? dest-path)))
                           (sxml  (load-xml path)))
                  (when verbose (print path))
                  (create-directory* (sys-dirname dest-path))
                  (call-with-output-file dest-path
                    (lambda (out)
                      (call-with-input-string (format-sxml-to-string (convert sxml))
                        (lambda (in)
                          (copy-port in out)
                          (display "\n<!-- not_yet_translated -->\n" out)))))))
              restargs))
  0)
