(*TOP*
 (item "Top")
 (chapter
  (item "ja/core_javascript_1.5_guide")
  (section
   ;;(item "ja/core_javascript_1.5_guide/table_of_contents_1.0")
   ;;(item "ja/core_javascript_1.5_guide/table_of_contents_2.0")
   (item "ja/core_javascript_1.5_guide/about")
   (item "ja/core_javascript_1.5_guide/javascript_overview")
   (item "ja/core_javascript_1.5_guide/core_language_features")
   ;;(item "ja/core_javascript_1.5_guide/values__variables__and_literals")
   (item "ja/core_javascript_1.5_guide/values")
   (item "ja/core_javascript_1.5_guide/variables")
   (item "ja/core_javascript_1.5_guide/constants")
   (item "ja/core_javascript_1.5_guide/literals")
   (item "ja/core_javascript_1.5_guide/unicode")
   (item "ja/core_javascript_1.5_guide/expressions_and_operators")
   (item "ja/core_javascript_1.5_guide/expressions")
   (item "ja/core_javascript_1.5_guide/operators")
   (subsection
    (item "ja/core_javascript_1.5_guide/operators/assignment_operators")
    (item "ja/core_javascript_1.5_guide/operators/comparison_operators")
    (item "ja/core_javascript_1.5_guide/operators/arithmetic_operators")
    (item "ja/core_javascript_1.5_guide/operators/bitwise_operators")
    (item "ja/core_javascript_1.5_guide/operators/logical_operators")
    (item "ja/core_javascript_1.5_guide/operators/string_operators")
    (item "ja/core_javascript_1.5_guide/operators/special_operators")
    )
   (item "ja/core_javascript_1.5_guide/regular_expressions")
   (subsection
    (item "ja/core_javascript_1.5_guide/creating_a_regular_expression")
    (item "ja/core_javascript_1.5_guide/writing_a_regular_expression_pattern")
    (item "ja/core_javascript_1.5_guide/working_with_regular_expressions")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/working_with_regular_expressions/using_parenthesized_substring_matches")
     (item "ja/core_javascript_1.5_guide/working_with_regular_expressions/advanced_searching_with_flags")
     (item "ja/core_javascript_1.5_guide/working_with_regular_expressions/examples_of_regular_expressions")
     )
    )
   (item "ja/core_javascript_1.5_guide/statements")
   (subsection
    (item "ja/core_javascript_1.5_guide/block_statement")
    (item "ja/core_javascript_1.5_guide/conditional_statements")
    (item "ja/core_javascript_1.5_guide/loop_statements")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/loop_statements/for_statement")
     (item "ja/core_javascript_1.5_guide/loop_statements/do...while_statement")
     (item "ja/core_javascript_1.5_guide/loop_statements/while_statement")
     (item "ja/core_javascript_1.5_guide/loop_statements/label_statement")
     (item "ja/core_javascript_1.5_guide/loop_statements/break_statement")
     (item "ja/core_javascript_1.5_guide/loop_statements/continue_statement")
     )
    (item "ja/core_javascript_1.5_guide/object_manipulation_statements")
    (item "ja/core_javascript_1.5_guide/comments")
    (item "ja/core_javascript_1.5_guide/exception_handling_statements")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/exception_handling_statements/throw_statement")
     (item "ja/core_javascript_1.5_guide/exception_handling_statements/try...catch_statement")
     )
    )
   (item "ja/core_javascript_1.5_guide/functions")
   (subsection
    (item "ja/core_javascript_1.5_guide/defining_functions")
    (item "ja/core_javascript_1.5_guide/calling_functions")
    (item "ja/core_javascript_1.5_guide/using_the_arguments_object")
    (item "ja/core_javascript_1.5_guide/predefined_functions")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/predefined_functions/eval_function")
     (item "ja/core_javascript_1.5_guide/predefined_functions/isfinite_function")
     (item "ja/core_javascript_1.5_guide/predefined_functions/isnan_function")
     (item "ja/core_javascript_1.5_guide/predefined_functions/parseint_and_parsefloat_functions")
     (item "ja/core_javascript_1.5_guide/predefined_functions/number_and_string_functions")
     (item "ja/core_javascript_1.5_guide/predefined_functions/escape_and_unescape_functions")
     )
    (item "ja/core_javascript_1.5_guide/working_with_closures")
    )
   (item "ja/core_javascript_1.5_guide/working_with_objects")
   (subsection
    (item "ja/core_javascript_1.5_guide/objects_and_properties")
    (item "ja/core_javascript_1.5_guide/creating_new_objects")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/creating_new_objects/using_object_initializers")
     (item "ja/core_javascript_1.5_guide/creating_new_objects/using_a_constructor_function")
     (item "ja/core_javascript_1.5_guide/creating_new_objects/indexing_object_properties")
     (item "ja/core_javascript_1.5_guide/creating_new_objects/defining_properties_for_an_object_type")
     (item "ja/core_javascript_1.5_guide/creating_new_objects/defining_methods")
    (item "ja/core_javascript_1.5_guide/creating_new_objects/using_this_for_object_references")
     (item "ja/core_javascript_1.5_guide/creating_new_objects/defining_getters_and_setters")
     (item "ja/core_javascript_1.5_guide/creating_new_objects/deleting_properties")
     )
    (item "ja/core_javascript_1.5_guide/predefined_core_objects")
    (subsection
     (item "ja/core_javascript_1.5_guide/predefined_core_objects/array_object")
     (item "ja/core_javascript_1.5_guide/predefined_core_objects/boolean_object")
     (item "ja/core_javascript_1.5_guide/predefined_core_objects/date_object")
     (item "ja/core_javascript_1.5_guide/predefined_core_objects/function_object")
     (item "ja/core_javascript_1.5_guide/predefined_core_objects/math_object")
     (item "ja/core_javascript_1.5_guide/predefined_core_objects/number_object")
     (item "ja/core_javascript_1.5_guide/predefined_core_objects/regexp_object")
     (item "ja/core_javascript_1.5_guide/predefined_core_objects/string_object")
     )
    )
   (item "ja/core_javascript_1.5_guide/inheritance")
   (item "ja/core_javascript_1.5_guide/working_with_arrays")
   (item "ja/core_javascript_1.5_guide/iterators_and_generators")
   (item "ja/core_javascript_1.5_guide/details_of_the_object_model")
   (subsection
    (item "ja/core_javascript_1.5_guide/class-based_vs._prototype-based_languages")
    (item "ja/core_javascript_1.5_guide/the_employee_example")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/the_employee_example/creating_the_hierarchy")
     (item "ja/core_javascript_1.5_guide/the_employee_example/object_properties")
     (subsubsubsection
      (item "ja/core_javascript_1.5_guide/the_employee_example/object_properties/adding_properties")
      (item "ja/core_javascript_1.5_guide/the_employee_example/object_properties/inheriting_properties")
      )
     (item "ja/core_javascript_1.5_guide/the_employee_example/more_flexible_constructors")
     )
    (item "ja/core_javascript_1.5_guide/property_inheritance_revisited")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/property_inheritance_revisited/local_versus_inherited_values")
     (item "ja/core_javascript_1.5_guide/property_inheritance_revisited/determining_instance_relationships")
     (item "ja/core_javascript_1.5_guide/property_inheritance_revisited/global_information_in_constructors")
     (item "ja/core_javascript_1.5_guide/property_inheritance_revisited/no_multiple_inheritance")
     )
    )
   (item "ja/core_javascript_1.5_guide/liveconnect_overview")
   (subsection
    (item "ja/core_javascript_1.5_guide/liveconnect_overview/working_with_wrappers")
    (item "ja/core_javascript_1.5_guide/liveconnect_overview/javascript_to_java_communication")
    (item "ja/core_javascript_1.5_guide/liveconnect_overview/java_to_javascript_communication")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/liveconnect_overview/java_to_javascript_communication/using_the_liveconnect_classes")
     )
    (item "ja/core_javascript_1.5_guide/liveconnect_overview/data_type_conversions")
    (subsubsection
     (item "ja/core_javascript_1.5_guide/liveconnect_overview/data_type_conversions/javascript_to_java_conversions")
     (item "ja/core_javascript_1.5_guide/liveconnect_overview/data_type_conversions/java_to_javascript_conversions")
     )
    )
   (item "ja/core_javascript_1.5_guide/processing_xml_with_e4x")
   (item "ja/core_javascript_1.5_guide/domexception")
   (item "ja/core_javascript_1.5_guide/error")
   (item "ja/core_javascript_1.5_guide/evalerror")
   (item "ja/core_javascript_1.5_guide/syntaxerror")
   (item "ja/core_javascript_1.5_guide/typeerror")
;;    (item "ja/core_javascript_1.5_guide/obsolete_pages")
;;    (subsection
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/block_statement")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/calling_functions")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/class-based_vs._prototype-based_languages")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/comments")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/conditional_statements")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/constants")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_a_regular_expression")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/defining_getters_and_setters")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/defining_methods")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/defining_properties_for_an_object_type")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/deleting_properties")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/indexing_object_properties")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/using_a_constructor_function")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/using_object_initializers")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/creating_new_objects/using_this_for_object_references")
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/data_type_conversions")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/data_type_conversions/java_to_javascript_conversions")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/data_type_conversions/javascript_to_java_conversions")
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/defining_functions")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/exception_handling_statements")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/exception_handling_statements/throw_statement")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/exception_handling_statements/try...catch_statement")
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/expressions")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/java_to_javascript_communication")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/java_to_javascript_communication/using_the_liveconnect_classes")
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/javascript_to_java_communication")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/literals")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/break_statement")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/continue_statement")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/do...while_statement")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/for_statement")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/label_statement")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/loop_statements/while_statement")
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/object_manipulation_statements")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/objects_and_properties")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/operators")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/arithmetic_operators")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/assignment_operators")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/bitwise_operators")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/comparison_operators")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/logical_operators")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/special_operators")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/operators/string_operators")
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/array_object")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/boolean_object")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/date_object")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/function_object")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/math_object")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/number_object")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/regexp_object")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_core_objects/string_object")
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/escape_and_unescape_functions")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/eval_function")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/isfinite_function")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/isnan_function")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/number_and_string_functions")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/predefined_functions/parseint_and_parsefloat_functions")
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/property_inheritance_revisited")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/property_inheritance_revisited/determining_instance_relationships")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/property_inheritance_revisited/global_information_in_constructors")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/property_inheritance_revisited/local_versus_inherited_values")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/property_inheritance_revisited/no_multiple_inheritance")
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example/creating_the_hierarchy")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example/more_flexible_constructors")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example/object_properties")
;;      (subsubsubsection
;;       (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example/object_properties/adding_properties")
;;       (item "ja/core_javascript_1.5_guide/obsolete_pages/the_employee_example/object_properties/inheriting_properties")
;;       )
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/unicode")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/using_the_arguments_object")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/values")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/variables")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/working_with_regular_expressions")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/working_with_regular_expressions/advanced_searching_with_flags")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/working_with_regular_expressions/examples_of_regular_expressions")
;;      (item "ja/core_javascript_1.5_guide/obsolete_pages/working_with_regular_expressions/using_parenthesized_substring_matches")
;;      )
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/working_with_wrappers")
;;     (item "ja/core_javascript_1.5_guide/obsolete_pages/writing_a_regular_expression_pattern")
;;     )
   )
  )
 (chapter
  (item "ja/core_javascript_1.5_reference")
  (section
   (item "ja/core_javascript_1.5_reference%2f%2freorg")
   (item "ja/core_javascript_1.5_reference/about")
   (subsection
    (item "ja/core_javascript_1.5_reference/about/formatting_conventions")
    )
   (item "ja/core_javascript_1.5_reference/global_objects")
   (subsection
    (item "ja/core_javascript_1.5_reference/global_objects/array")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/array/concat")
     (item "ja/core_javascript_1.5_reference/global_objects/array/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/array/every")
     (item "ja/core_javascript_1.5_reference/global_objects/array/filter")
     (item "ja/core_javascript_1.5_reference/global_objects/array/foreach")
     (item "ja/core_javascript_1.5_reference/global_objects/array/index")
     (item "ja/core_javascript_1.5_reference/global_objects/array/indexof")
     (item "ja/core_javascript_1.5_reference/global_objects/array/input")
     (item "ja/core_javascript_1.5_reference/global_objects/array/join")
     (item "ja/core_javascript_1.5_reference/global_objects/array/lastindexof")
     (item "ja/core_javascript_1.5_reference/global_objects/array/length")
     (item "ja/core_javascript_1.5_reference/global_objects/array/map")
     (item "ja/core_javascript_1.5_reference/global_objects/array/pop")
     (item "ja/core_javascript_1.5_reference/global_objects/array/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/array/push")
     (item "ja/core_javascript_1.5_reference/global_objects/array/reduce")
     (item "ja/core_javascript_1.5_reference/global_objects/array/reduceright")
     (item "ja/core_javascript_1.5_reference/global_objects/array/reverse")
     (item "ja/core_javascript_1.5_reference/global_objects/array/shift")
     (item "ja/core_javascript_1.5_reference/global_objects/array/slice")
     (item "ja/core_javascript_1.5_reference/global_objects/array/some")
     (item "ja/core_javascript_1.5_reference/global_objects/array/sort")
     (item "ja/core_javascript_1.5_reference/global_objects/array/splice")
     (item "ja/core_javascript_1.5_reference/global_objects/array/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/array/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/array/unshift")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/boolean")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/boolean/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/boolean/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/boolean/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/boolean/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/boolean/valueof")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/date")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/date/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getdate")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getday")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getfullyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/gethours")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getmilliseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getminutes")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getmonth")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/gettime")
     (item "ja/core_javascript_1.5_reference/global_objects/date/gettimezoneoffset")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcdate")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcday")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcfullyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutchours")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcmilliseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcminutes")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcmonth")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getutcseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/getyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/now")
     (item "ja/core_javascript_1.5_reference/global_objects/date/parse")
     (item "ja/core_javascript_1.5_reference/global_objects/date/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setdate")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setfullyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/sethours")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setmilliseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setminutes")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setmonth")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/settime")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcdate")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcfullyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutchours")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcmilliseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcminutes")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcmonth")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setutcseconds")
     (item "ja/core_javascript_1.5_reference/global_objects/date/setyear")
     (item "ja/core_javascript_1.5_reference/global_objects/date/todatestring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/togmtstring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tolocaledatestring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tolocaleformat")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tolocalestring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tolocaletimestring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/date/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/totimestring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/toutcstring")
     (item "ja/core_javascript_1.5_reference/global_objects/date/utc")
     (item "ja/core_javascript_1.5_reference/global_objects/date/valueof")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/error")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/error/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/error/message")
     (item "ja/core_javascript_1.5_reference/global_objects/error/name")
     (item "ja/core_javascript_1.5_reference/global_objects/error/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/error/stack")
     (item "ja/core_javascript_1.5_reference/global_objects/error/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/error/tostring")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/evalerror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/evalerror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/evalerror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/evalerror/prototype")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/function")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/function/apply")
     (item "ja/core_javascript_1.5_reference/global_objects/function/arguments")
     (item "ja/core_javascript_1.5_reference/global_objects/function/arity")
     (item "ja/core_javascript_1.5_reference/global_objects/function/call")
     (item "ja/core_javascript_1.5_reference/global_objects/function/caller")
     (item "ja/core_javascript_1.5_reference/global_objects/function/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/function/length")
     (item "ja/core_javascript_1.5_reference/global_objects/function/name")
     (item "ja/core_javascript_1.5_reference/global_objects/function/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/function/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/function/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/function/valueof")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/java")
    (item "ja/core_javascript_1.5_reference/global_objects/javaarray")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/javaarray/length")
     (item "ja/core_javascript_1.5_reference/global_objects/javaarray/tostring")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/javaclass")
    (item "ja/core_javascript_1.5_reference/global_objects/javaobject")
    (item "ja/core_javascript_1.5_reference/global_objects/javapackage")
    (item "ja/core_javascript_1.5_reference/global_objects/math")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/math/abs")
     (item "ja/core_javascript_1.5_reference/global_objects/math/acos")
     (item "ja/core_javascript_1.5_reference/global_objects/math/asin")
     (item "ja/core_javascript_1.5_reference/global_objects/math/atan")
     (item "ja/core_javascript_1.5_reference/global_objects/math/atan2")
     (item "ja/core_javascript_1.5_reference/global_objects/math/ceil")
     (item "ja/core_javascript_1.5_reference/global_objects/math/cos")
     (item "ja/core_javascript_1.5_reference/global_objects/math/e")
     (item "ja/core_javascript_1.5_reference/global_objects/math/exp")
     (item "ja/core_javascript_1.5_reference/global_objects/math/floor")
     (item "ja/core_javascript_1.5_reference/global_objects/math/ln10")
     (item "ja/core_javascript_1.5_reference/global_objects/math/ln2")
     (item "ja/core_javascript_1.5_reference/global_objects/math/log")
     (item "ja/core_javascript_1.5_reference/global_objects/math/log10e")
     (item "ja/core_javascript_1.5_reference/global_objects/math/log2e")
     (item "ja/core_javascript_1.5_reference/global_objects/math/max")
     (item "ja/core_javascript_1.5_reference/global_objects/math/min")
     (item "ja/core_javascript_1.5_reference/global_objects/math/pi")
     (item "ja/core_javascript_1.5_reference/global_objects/math/pow")
     (item "ja/core_javascript_1.5_reference/global_objects/math/random")
     (item "ja/core_javascript_1.5_reference/global_objects/math/round")
     (item "ja/core_javascript_1.5_reference/global_objects/math/sin")
     (item "ja/core_javascript_1.5_reference/global_objects/math/sqrt")
     (item "ja/core_javascript_1.5_reference/global_objects/math/sqrt1_2")
     (item "ja/core_javascript_1.5_reference/global_objects/math/sqrt2")
     (item "ja/core_javascript_1.5_reference/global_objects/math/tan")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/netscape")
    (item "ja/core_javascript_1.5_reference/global_objects/number")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/number/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/number/max_value")
     (item "ja/core_javascript_1.5_reference/global_objects/number/min_value")
     (item "ja/core_javascript_1.5_reference/global_objects/number/nan")
     (item "ja/core_javascript_1.5_reference/global_objects/number/negative_infinity")
     (item "ja/core_javascript_1.5_reference/global_objects/number/positive_infinity")
     (item "ja/core_javascript_1.5_reference/global_objects/number/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/number/toexponential")
     (item "ja/core_javascript_1.5_reference/global_objects/number/tofixed")
     (item "ja/core_javascript_1.5_reference/global_objects/number/tolocalestring")
     (item "ja/core_javascript_1.5_reference/global_objects/number/toprecision")
     (item "ja/core_javascript_1.5_reference/global_objects/number/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/number/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/number/valueof")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/object")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/object/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/object/create")
     (item "ja/core_javascript_1.5_reference/global_objects/object/definegetter")
     (item "ja/core_javascript_1.5_reference/global_objects/object/defineproperties")
     (item "ja/core_javascript_1.5_reference/global_objects/object/defineproperty")
     (item "ja/core_javascript_1.5_reference/global_objects/object/definesetter")
     (item "ja/core_javascript_1.5_reference/global_objects/object/eval")
     (item "ja/core_javascript_1.5_reference/global_objects/object/getownpropertydescriptor")
     (item "ja/core_javascript_1.5_reference/global_objects/object/getprototypeof")
     (item "ja/core_javascript_1.5_reference/global_objects/object/hasownproperty")
     (item "ja/core_javascript_1.5_reference/global_objects/object/isprototypeof")
     (item "ja/core_javascript_1.5_reference/global_objects/object/keys")
     (item "ja/core_javascript_1.5_reference/global_objects/object/lookupgetter")
     (item "ja/core_javascript_1.5_reference/global_objects/object/lookupsetter")
     (item "ja/core_javascript_1.5_reference/global_objects/object/nosuchmethod")
     (item "ja/core_javascript_1.5_reference/global_objects/object/parent")
     (item "ja/core_javascript_1.5_reference/global_objects/object/propertyisenumerable")
     (item "ja/core_javascript_1.5_reference/global_objects/object/proto")
     (item "ja/core_javascript_1.5_reference/global_objects/object/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/object/temp")
     (item "ja/core_javascript_1.5_reference/global_objects/object/tolocalestring")
     (item "ja/core_javascript_1.5_reference/global_objects/object/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/object/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/object/unwatch")
     (item "ja/core_javascript_1.5_reference/global_objects/object/valueof")
     (item "ja/core_javascript_1.5_reference/global_objects/object/watch")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/packages")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/packages/classname")
     (item "ja/core_javascript_1.5_reference/global_objects/packages/java")
     (item "ja/core_javascript_1.5_reference/global_objects/packages/netscape")
     (item "ja/core_javascript_1.5_reference/global_objects/packages/sun")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/range")
    (item "ja/core_javascript_1.5_reference/global_objects/rangeerror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/rangeerror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/rangeerror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/rangeerror/prototype")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/referenceerror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/referenceerror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/referenceerror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/referenceerror/prototype")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/regexp")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/exec")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/global")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/ignorecase")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/lastindex")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/multiline")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/source")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/test")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/regexp/tostring")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/string")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/string/anchor")
     (item "ja/core_javascript_1.5_reference/global_objects/string/big")
     (item "ja/core_javascript_1.5_reference/global_objects/string/blink")
     (item "ja/core_javascript_1.5_reference/global_objects/string/bold")
     (item "ja/core_javascript_1.5_reference/global_objects/string/charat")
     (item "ja/core_javascript_1.5_reference/global_objects/string/charcodeat")
     (item "ja/core_javascript_1.5_reference/global_objects/string/concat")
     (item "ja/core_javascript_1.5_reference/global_objects/string/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/string/fixed")
     (item "ja/core_javascript_1.5_reference/global_objects/string/fontcolor")
     (item "ja/core_javascript_1.5_reference/global_objects/string/fontsize")
     (item "ja/core_javascript_1.5_reference/global_objects/string/fromcharcode")
     (item "ja/core_javascript_1.5_reference/global_objects/string/indexof")
     (item "ja/core_javascript_1.5_reference/global_objects/string/italics")
     (item "ja/core_javascript_1.5_reference/global_objects/string/lastindexof")
     (item "ja/core_javascript_1.5_reference/global_objects/string/length")
     (item "ja/core_javascript_1.5_reference/global_objects/string/link")
     (item "ja/core_javascript_1.5_reference/global_objects/string/localecompare")
     (item "ja/core_javascript_1.5_reference/global_objects/string/match")
     (item "ja/core_javascript_1.5_reference/global_objects/string/prototype")
     (item "ja/core_javascript_1.5_reference/global_objects/string/quote")
     (item "ja/core_javascript_1.5_reference/global_objects/string/replace")
     (item "ja/core_javascript_1.5_reference/global_objects/string/search")
     (item "ja/core_javascript_1.5_reference/global_objects/string/slice")
     (item "ja/core_javascript_1.5_reference/global_objects/string/small")
     (item "ja/core_javascript_1.5_reference/global_objects/string/split")
     (item "ja/core_javascript_1.5_reference/global_objects/string/strike")
     (item "ja/core_javascript_1.5_reference/global_objects/string/sub")
     (item "ja/core_javascript_1.5_reference/global_objects/string/substr")
     (item "ja/core_javascript_1.5_reference/global_objects/string/substring")
     (item "ja/core_javascript_1.5_reference/global_objects/string/sup")
     (item "ja/core_javascript_1.5_reference/global_objects/string/tolocalelowercase")
     (item "ja/core_javascript_1.5_reference/global_objects/string/tolocaleuppercase")
     (item "ja/core_javascript_1.5_reference/global_objects/string/tolowercase")
     (item "ja/core_javascript_1.5_reference/global_objects/string/tosource")
     (item "ja/core_javascript_1.5_reference/global_objects/string/tostring")
     (item "ja/core_javascript_1.5_reference/global_objects/string/touppercase")
     (item "ja/core_javascript_1.5_reference/global_objects/string/trim")
     (item "ja/core_javascript_1.5_reference/global_objects/string/trimleft")
     (item "ja/core_javascript_1.5_reference/global_objects/string/trimright")
     (item "ja/core_javascript_1.5_reference/global_objects/string/valueof")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/sun")
    (item "ja/core_javascript_1.5_reference/global_objects/syntaxerror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/syntaxerror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/syntaxerror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/syntaxerror/prototype")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/typeerror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/typeerror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/typeerror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/typeerror/prototype")
     )
    (item "ja/core_javascript_1.5_reference/global_objects/urierror")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/global_objects/urierror/constructor")
     (item "ja/core_javascript_1.5_reference/global_objects/urierror/name")
     (item "ja/core_javascript_1.5_reference/global_objects/urierror/prototype")
     )
    )
   (item "ja/core_javascript_1.5_reference/objects")
   (subsection
    (item "ja/core_javascript_1.5_reference/objects/array")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/objects/array/reduce")
     (item "ja/core_javascript_1.5_reference/objects/array/reduceright")
     )
    (item "ja/core_javascript_1.5_reference/objects/number")
    )
   (item "ja/core_javascript_1.5_reference/liveconnect")
   (subsection
    (item "ja/core_javascript_1.5_reference/liveconnect/jsexception")
    (item "ja/core_javascript_1.5_reference/liveconnect/jsobject")
    )
   (item "ja/core_javascript_1.5_reference/global_properties")
   (subsection
    (item "ja/core_javascript_1.5_reference/global_properties/infinity")
    (item "ja/core_javascript_1.5_reference/global_properties/nan")
    (item "ja/core_javascript_1.5_reference/global_properties/undefined")
    )
   (item "ja/core_javascript_1.5_reference/global_functions")
   (subsection
    (item "ja/core_javascript_1.5_reference/global_functions/decodeuri")
    (item "ja/core_javascript_1.5_reference/global_functions/decodeuricomponent")
    (item "ja/core_javascript_1.5_reference/global_functions/encodeuri")
    (item "ja/core_javascript_1.5_reference/global_functions/encodeuricomponent")
    (item "ja/core_javascript_1.5_reference/global_functions/eval")
    (item "ja/core_javascript_1.5_reference/global_functions/isfinite")
    (item "ja/core_javascript_1.5_reference/global_functions/isnan")
    (item "ja/core_javascript_1.5_reference/global_functions/parsefloat")
    (item "ja/core_javascript_1.5_reference/global_functions/parseint")
    )
   (item "ja/core_javascript_1.5_reference/functions")
   (subsection
    (item "ja/core_javascript_1.5_reference/functions/arguments")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/functions/arguments/callee")
     (item "ja/core_javascript_1.5_reference/functions/arguments/caller")
     (item "ja/core_javascript_1.5_reference/functions/arguments/length")
     )
    )
;;    (item "ja/core_javascript_1.5_reference/functions_and_function_scope")
;;    (subsection
;;     (item "ja/core_javascript_1.5_reference/functions_and_function_scope/arguments")
;;     (subsubsection
;;      (item "ja/core_javascript_1.5_reference/functions_and_function_scope/arguments/callee")
;;      (item "ja/core_javascript_1.5_reference/functions_and_function_scope/arguments/caller")
;;      (item "ja/core_javascript_1.5_reference/functions_and_function_scope/arguments/length")
;;      )
;;     )
   (item "ja/core_javascript_1.5_reference/statements")
   (subsection
    (item "ja/core_javascript_1.5_reference/statements/block")
    (item "ja/core_javascript_1.5_reference/statements/break")
    (item "ja/core_javascript_1.5_reference/statements/const")
    (item "ja/core_javascript_1.5_reference/statements/continue")
    (item "ja/core_javascript_1.5_reference/statements/do...while")
    (item "ja/core_javascript_1.5_reference/statements/export")
    (item "ja/core_javascript_1.5_reference/statements/for...in")
    (item "ja/core_javascript_1.5_reference/statements/for")
    (item "ja/core_javascript_1.5_reference/statements/for_each...in")
    (item "ja/core_javascript_1.5_reference/statements/function")
    (item "ja/core_javascript_1.5_reference/statements/if...else")
    (item "ja/core_javascript_1.5_reference/statements/import")
    (item "ja/core_javascript_1.5_reference/statements/label")
    (item "ja/core_javascript_1.5_reference/statements/let")
    (item "ja/core_javascript_1.5_reference/statements/return")
    (item "ja/core_javascript_1.5_reference/statements/switch")
    (item "ja/core_javascript_1.5_reference/statements/throw")
    (item "ja/core_javascript_1.5_reference/statements/try...catch")
    (item "ja/core_javascript_1.5_reference/statements/var")
    (item "ja/core_javascript_1.5_reference/statements/while")
    (item "ja/core_javascript_1.5_reference/statements/with")
    )
   (item "ja/core_javascript_1.5_reference/operators")
   (subsection
    (item "ja/core_javascript_1.5_reference/operators/arithmetic_operators")
    (item "ja/core_javascript_1.5_reference/operators/assignment_operators")
    (item "ja/core_javascript_1.5_reference/operators/bitwise_operators")
    (item "ja/core_javascript_1.5_reference/operators/comparison_operators")
    (item "ja/core_javascript_1.5_reference/operators/logical_operators")
    (item "ja/core_javascript_1.5_reference/operators/member_operators")
    (item "ja/core_javascript_1.5_reference/operators/string_operators")
    (item "ja/core_javascript_1.5_reference/operators/special_operators")
    (subsubsection
     (item "ja/core_javascript_1.5_reference/operators/special_operators/comma_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/conditional_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/delete_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/function_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/get_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/in_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/instanceof_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/new_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/set_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/this_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/typeof_operator")
     (item "ja/core_javascript_1.5_reference/operators/special_operators/void_operator")
     )
    (item "ja/core_javascript_1.5_reference/operators/operator_precedence")
    )
   (item "ja/core_javascript_1.5_reference/reserved_words")
   (item "ja/core_javascript_1.5_reference/deprecated_features")
   (item "ja/core_javascript_1.5_reference/symbols")
;;    (subsection
;;     (item "ja/core_javascript_1.5_reference/symbols/page_title")
;;     )
   )
  )
 (chapter
  (item "ja/new_in_javascript")
  (section
   (item "ja/new_in_javascript_1.1")
   (item "ja/new_in_javascript_1.2")
   (item "ja/new_in_javascript_1.3")
   (item "ja/new_in_javascript_1.4")
   (item "ja/new_in_javascript_1.5")
   (item "ja/new_in_javascript_1.6")
   (item "ja/new_in_javascript_1.7")
   (item "ja/new_in_javascript_1.8")
   (item "ja/new_in_javascript_1.8.1")
   (item "ja/new_in_javascript_1.9")
   )
  )
 (chapter
  (item "ja/gecko_dom_reference")
  (section
   (item "ja/gecko_dom_reference/preface")
   (item "ja/gecko_dom_reference/introduction")
   (item "ja/gecko_dom_reference/examples")
   )
  )
 (chapter
  (item "ja/dom")
  (section
   (item "ja/dom/attr")
   (item "ja/dom/base")
   (item "ja/dom/cdatasection")
   (item "ja/dom/characterdata")
   (item "ja/dom/comment")
   (item "ja/dom/cssstyledeclaration")
   (item "ja/dom/detecting_document_width_and_height_changes")
   (item "ja/dom/dispatchevent_example")
   (item "ja/dom/domconfiguration")
   (item "ja/dom/domerror")
   (item "ja/dom/domerrorhandler")
   (item "ja/dom/domexception")
   (item "ja/dom/domimplementation.createdocument")
   (item "ja/dom/domimplementation.createdocumenttype")
   (item "ja/dom/domimplementation")
   (item "ja/dom/domimplementationlist")
   (item "ja/dom/domimplementationregistry")
   (item "ja/dom/domimplementationsource")
   (item "ja/dom/domlocator")
   (item "ja/dom/domobject")
   (item "ja/dom/domstring")
   (item "ja/dom/domstringlist")
   (item "ja/dom/domtimestamp")
   (item "ja/dom/domtokenlist")
   (item "ja/dom/domuserdata")
   (item "ja/dom/entity")
   (item "ja/dom/entityreference")
   (item "ja/dom/eventtarget")
   (item "ja/dom/sharedworker")
   (item "ja/dom/storage")
   (item "ja/dom/locating_dom_elements_using_selectors")
   (item "ja/dom/manipulating_the_browser_history")
   (item "ja/dom/mouse_gesture_events")
   (item "ja/dom/namednodemap")
   (item "ja/dom/namelist")
   (item "ja/dom/nodelist")
   (item "ja/dom/notation")
   (item "ja/dom/processinginstruction")
   (item "ja/dom/typeinfo")
   (item "ja/dom/userdatahandler")
   (item "ja/dom/using_dynamic_styling_information")
   (item "ja/dom/whitespace_template")
   (item "ja/dom/worker")
   (item "ja/dom/wrong_document_err_note")

   (item "ja/dom/css")
   (subsection
    (item "ja/dom/css/background")
    )
   (item "ja/dom/cssrule")
   (subsection
    (item "ja/dom/cssrule.csstext")
    (item "ja/dom/cssrule.parentstylesheet")
    (item "ja/dom/cssrule.selectortext")
    (item "ja/dom/cssrule.style")
    )
   (item "ja/dom/document")
   (subsection
    (item "ja/dom/document.activeelement")
    (item "ja/dom/document.adoptnode")
    (item "ja/dom/document.alinkcolor")
    (item "ja/dom/document.anchors")
    (item "ja/dom/document.applets")
    (item "ja/dom/document.async")
    (item "ja/dom/document.baseuriobject")
    (item "ja/dom/document.bgcolor")
    (item "ja/dom/document.body")
    (item "ja/dom/document.characterset")
    (item "ja/dom/document.clear")
    (item "ja/dom/document.close")
    (item "ja/dom/document.compatmode")
    (item "ja/dom/document.contenttype")
    (item "ja/dom/document.cookie")
    (item "ja/dom/document.createattribute")
    (item "ja/dom/document.createcdatasection")
    (item "ja/dom/document.createcomment")
    (item "ja/dom/document.createdocumentfragment")
    (item "ja/dom/document.createelement")
    (item "ja/dom/document.createelementns")
    (item "ja/dom/document.createentityreference")
    (item "ja/dom/document.createevent")
    (item "ja/dom/document.createexpression")
    (item "ja/dom/document.createnodeiterator")
    (item "ja/dom/document.creatensresolver")
    (item "ja/dom/document.createprocessinginstruction")
    (item "ja/dom/document.createrange")
    (item "ja/dom/document.createtextnode")
    (item "ja/dom/document.createtreewalker")
    (item "ja/dom/document.defaultview")
    (item "ja/dom/document.designmode")
    (item "ja/dom/document.dir")
    (item "ja/dom/document.doctype")
    (item "ja/dom/document.documentelement")
    (item "ja/dom/document.documenturi")
    (item "ja/dom/document.documenturiobject")
    (item "ja/dom/document.domain")
    (item "ja/dom/document.domconfig")
    (item "ja/dom/document.elementfrompoint")
    (item "ja/dom/document.embeds")
    (item "ja/dom/document.evaluate")
    (item "ja/dom/document.fgcolor")
    (item "ja/dom/document.firstchild")
    (item "ja/dom/document.forms")
    (item "ja/dom/document.getboxobjectfor")
    (item "ja/dom/document.getelementbyid")
    (item "ja/dom/document.getelementsbyclassname")
    (item "ja/dom/document.getelementsbyname")
    (item "ja/dom/document.getelementsbytagname")
    (item "ja/dom/document.getelementsbytagnamens")
    (item "ja/dom/document.hasfocus")
    (item "ja/dom/document.height")
    (item "ja/dom/document.images")
    (item "ja/dom/document.implementation")
    (item "ja/dom/document.importnode")
    (item "ja/dom/document.inputencoding")
    (item "ja/dom/document.lastmodified")
    (item "ja/dom/document.linkcolor")
    (item "ja/dom/document.links")
    (item "ja/dom/document.load")
    (item "ja/dom/document.loadoverlay")
    (item "ja/dom/document.location")
    (item "ja/dom/document.namespaceuri")
    (item "ja/dom/document.nodeprincipal")
    (item "ja/dom/document.onreadystatechange")
    (item "ja/dom/document.open")
    (item "ja/dom/document.plugins")
    (item "ja/dom/document.popupnode")
    (item "ja/dom/document.queryselector")
    (item "ja/dom/document.queryselectorall")
    (item "ja/dom/document.readystate")
    (item "ja/dom/document.referrer")
    (item "ja/dom/document.stylesheets")
    (item "ja/dom/document.textcontent")
    (item "ja/dom/document.title")
    (item "ja/dom/document.tooltipnode")
    (item "ja/dom/document.url")
    (item "ja/dom/document.vlinkcolor")
    (item "ja/dom/document.width")
    (item "ja/dom/document.write")
    (item "ja/dom/document.writeln")
    (item "ja/dom/document.xmlencoding")
    (item "ja/dom/document.xmlversion")
    )
   (item "ja/dom/documentfragment")
   (item "ja/dom/documenttype")
   (item "ja/dom/element")
   (subsection
    (item "ja/dom/element.addeventlistener")
    (item "ja/dom/element.appendchild")
    (item "ja/dom/element.attributes")
    (item "ja/dom/element.baseuriobject")
    (item "ja/dom/element.blur")
    (item "ja/dom/element.childelementcount")
    (item "ja/dom/element.childnodes")
    (item "ja/dom/element.children")
    (item "ja/dom/element.classlist")
    (item "ja/dom/element.classname")
    (item "ja/dom/element.click")
    (item "ja/dom/element.clientheight")
    (item "ja/dom/element.clientleft")
    (item "ja/dom/element.clienttop")
    (item "ja/dom/element.clientwidth")
    (item "ja/dom/element.contenteditable")
    (item "ja/dom/element.dir")
    (item "ja/dom/element.dispatchevent")
    (item "ja/dom/element.firstchild")
    (item "ja/dom/element.firstelementchild")
    (item "ja/dom/element.focus")
    (item "ja/dom/element.getattribute")
    (item "ja/dom/element.getattributenode")
    (item "ja/dom/element.getattributenodens")
    (item "ja/dom/element.getattributens")
    (item "ja/dom/element.getboundingclientrect")
    (item "ja/dom/element.getclientrects")
    (item "ja/dom/element.getelementsbyclassname")
    (item "ja/dom/element.getelementsbytagname")
    (item "ja/dom/element.getelementsbytagnamens")
    (item "ja/dom/element.hasattribute")
    (item "ja/dom/element.hasattributens")
    (item "ja/dom/element.hasattributes")
    (item "ja/dom/element.haschildnodes")
    (item "ja/dom/element.id")
    (item "ja/dom/element.innerhtml")
    (item "ja/dom/element.insertbefore")
    (item "ja/dom/element.iscontenteditable")
    (item "ja/dom/element.issupported")
    (item "ja/dom/element.item")
    (item "ja/dom/element.lang")
    (item "ja/dom/element.lastchild")
    (item "ja/dom/element.lastelementchild")
    (item "ja/dom/element.length")
    (item "ja/dom/element.localname")
    (item "ja/dom/element.name")
    (item "ja/dom/element.namespaceuri")
    (item "ja/dom/element.nextelementsibling")
    (item "ja/dom/element.nextsibling")
    (item "ja/dom/element.nodename")
    (item "ja/dom/element.nodetype")
    (item "ja/dom/element.normalize")
    (item "ja/dom/element.offsetheight")
    (item "ja/dom/element.offsetleft")
    (item "ja/dom/element.offsetparent")
    (item "ja/dom/element.offsettop")
    (item "ja/dom/element.offsetwidth")
    (item "ja/dom/element.onblur")
    (item "ja/dom/element.onchange")
    (item "ja/dom/element.onclick")
    (item "ja/dom/element.oncopy")
    (item "ja/dom/element.oncut")
    (item "ja/dom/element.ondblclick")
    (item "ja/dom/element.onfocus")
    (item "ja/dom/element.onkeydown")
    (item "ja/dom/element.onkeypress")
    (item "ja/dom/element.onkeyup")
    (item "ja/dom/element.onmousedown")
    (item "ja/dom/element.onmousemove")
    (item "ja/dom/element.onmouseout")
    (item "ja/dom/element.onmouseover")
    (item "ja/dom/element.onmouseup")
    (item "ja/dom/element.onpaste")
    (item "ja/dom/element.onresize")
    (item "ja/dom/element.onscroll")
    (item "ja/dom/element.ownerdocument")
    (item "ja/dom/element.parentnode")
    (item "ja/dom/element.prefix")
    (item "ja/dom/element.previouselementsibling")
    (item "ja/dom/element.previoussibling")
    (item "ja/dom/element.queryselector")
    (item "ja/dom/element.queryselectorall")
    (item "ja/dom/element.removeattribute")
    (item "ja/dom/element.removeattributenode")
    (item "ja/dom/element.removeattributens")
    (item "ja/dom/element.removechild")
    (item "ja/dom/element.removeeventlistener")
    (item "ja/dom/element.replacechild")
    (item "ja/dom/element.scrollheight")
    (item "ja/dom/element.scrollintoview")
    (item "ja/dom/element.scrollleft")
    (item "ja/dom/element.scrolltop")
    (item "ja/dom/element.scrollwidth")
    (item "ja/dom/element.setattribute")
    (item "ja/dom/element.setattributenode")
    (item "ja/dom/element.setattributenodens")
    (item "ja/dom/element.setattributens")
    (item "ja/dom/element.style")
    (item "ja/dom/element.supports")
    (item "ja/dom/element.tabindex")
    (item "ja/dom/element.tagname")
    (item "ja/dom/element.title")
    )
   (item "ja/dom/event")
   (subsection
    (item "ja/dom/event/comparison_of_event_targets")
    (item "ja/dom/event.altkey")
    (item "ja/dom/event.bubbles")
    (item "ja/dom/event.button")
    (item "ja/dom/event.cancelable")
    (item "ja/dom/event.cancelbubble")
    (item "ja/dom/event.charcode")
    (item "ja/dom/event.clientx")
    (item "ja/dom/event.clienty")
    (item "ja/dom/event.ctrlkey")
    (item "ja/dom/event.currenttarget")
    (item "ja/dom/event.detail")
    (item "ja/dom/event.eventphase")
    (item "ja/dom/event.explicitoriginaltarget")
    (item "ja/dom/event.initevent")
    (item "ja/dom/event.initkeyevent")
    (item "ja/dom/event.initmouseevent")
    (item "ja/dom/event.inituievent")
    (item "ja/dom/event.ischar")
    (item "ja/dom/event.keycode")
    (item "ja/dom/event.layerx")
    (item "ja/dom/event.layery")
    (item "ja/dom/event.metakey")
    (item "ja/dom/event.originaltarget")
    (item "ja/dom/event.pagex")
    (item "ja/dom/event.pagey")
    (item "ja/dom/event.preventdefault")
    (item "ja/dom/event.relatedtarget")
    (item "ja/dom/event.screenx")
    (item "ja/dom/event.screeny")
    (item "ja/dom/event.shiftkey")
    (item "ja/dom/event.stoppropagation")
    (item "ja/dom/event.target")
    (item "ja/dom/event.timestamp")
    (item "ja/dom/event.type")
    (item "ja/dom/event.view")
    (item "ja/dom/event.which")
    (item "ja/dom/event/uievent")
    (subsubsection
     (item "ja/dom/event/uievent/keyevent")
     )
    )
   (item "ja/dom/file")
   (subsection
    (item "ja/dom/file.filename")
    (item "ja/dom/file.filesize")
    (item "ja/dom/file.getasbinary")
    (item "ja/dom/file.getasdataurl")
    (item "ja/dom/file.getastext")
    (item "ja/dom/file.name")
    (item "ja/dom/file.size")
    (item "ja/dom/file.type")
    )
   (item "ja/dom/fileerror")
   (item "ja/dom/filelist")
   (item "ja/dom/filereader")

   (item "ja/dom/node")
   (subsection
    (item "ja/dom/node.appendchild")
    (item "ja/dom/node.attributes")
    (item "ja/dom/node.childnodes")
    (item "ja/dom/node.clonenode")
    (item "ja/dom/node.comparedocumentposition")
    (item "ja/dom/node.firstchild")
    (item "ja/dom/node.getuserdata")
    (item "ja/dom/node.hasattributes")
    (item "ja/dom/node.haschildnodes")
    (item "ja/dom/node.insertbefore")
    (item "ja/dom/node.isdefaultnamespace")
    (item "ja/dom/node.issupported")
    (item "ja/dom/node.lastchild")
    (item "ja/dom/node.localname")
    (item "ja/dom/node.lookupnamespaceuri")
    (item "ja/dom/node.lookupprefix")
    (item "ja/dom/node.mozmatchesselector")
    (item "ja/dom/node.namespaceuri")
    (item "ja/dom/node.nextsibling")
    (item "ja/dom/node.nodename")
    (item "ja/dom/node.nodeprincipal")
    (item "ja/dom/node.nodetype")
    (item "ja/dom/node.nodevalue")
    (item "ja/dom/node.normalize")
    (item "ja/dom/node.ownerdocument")
    (item "ja/dom/node.parentnode")
    (item "ja/dom/node.prefix")
    (item "ja/dom/node.previoussibling")
    (item "ja/dom/node.removechild")
    (item "ja/dom/node.replacechild")
    (item "ja/dom/node.setuserdata")
    (item "ja/dom/node.textcontent")
    (item "ja/dom/node/appendchild")
    (item "ja/dom/node/attributes")
    (item "ja/dom/node/childnodes")
    (item "ja/dom/node/clonenode")
    (item "ja/dom/node/comparedocumentposition")
    (item "ja/dom/node/firstchild")
    (item "ja/dom/node/hasattributes")
    (item "ja/dom/node/haschildnodes")
    (item "ja/dom/node/insertbefore")
    (item "ja/dom/node/issupported")
    (item "ja/dom/node/lastchild")
    (item "ja/dom/node/localname")
    (item "ja/dom/node/namespaceuri")
    (item "ja/dom/node/nextsibling")
    (item "ja/dom/node/nodename")
    (item "ja/dom/node/nodeprincipal")
    (item "ja/dom/node/nodetype")
    (item "ja/dom/node/nodevalue")
    (item "ja/dom/node/normalize")
    (item "ja/dom/node/ownerdocument")
    (item "ja/dom/node/parentnode")
    (item "ja/dom/node/prefix")
    (item "ja/dom/node/previoussibling")
    (item "ja/dom/node/replacechild")
    (item "ja/dom/node/textcontent")
    )
   (item "ja/dom/nodeiterator")
   (subsection
    (item "ja/dom/nodeiterator.detach")
    (item "ja/dom/nodeiterator.expandentityreferences")
    (item "ja/dom/nodeiterator.filter")
    (item "ja/dom/nodeiterator.nextnode")
    (item "ja/dom/nodeiterator.pointerbeforereferencenode")
    (item "ja/dom/nodeiterator.previousnode")
    (item "ja/dom/nodeiterator.referencenode")
    (item "ja/dom/nodeiterator.root")
    (item "ja/dom/nodeiterator.whattoshow")
    )
   (item "ja/dom/range")
   (subsection
    (item "ja/dom/range.clonecontents")
    (item "ja/dom/range.clonerange")
    (item "ja/dom/range.collapse")
    (item "ja/dom/range.collapsed")
    (item "ja/dom/range.commonancestorcontainer")
    (item "ja/dom/range.compareboundarypoints")
    (item "ja/dom/range.comparenode")
    (item "ja/dom/range.comparepoint")
    (item "ja/dom/range.createcontextualfragment")
    (item "ja/dom/range.deletecontents")
    (item "ja/dom/range.detach")
    (item "ja/dom/range.endcontainer")
    (item "ja/dom/range.endoffset")
    (item "ja/dom/range.extractcontents")
    (item "ja/dom/range.insertnode")
    (item "ja/dom/range.intersectsnode")
    (item "ja/dom/range.ispointinrange")
    (item "ja/dom/range.selectnode")
    (item "ja/dom/range.selectnodecontents")
    (item "ja/dom/range.setend")
    (item "ja/dom/range.setendafter")
    (item "ja/dom/range.setendbefore")
    (item "ja/dom/range.setstart")
    (item "ja/dom/range.setstartafter")
    (item "ja/dom/range.setstartbefore")
    (item "ja/dom/range.startcontainer")
    (item "ja/dom/range.startoffset")
    (item "ja/dom/range.surroundcontents")
    (item "ja/dom/range.tostring")
    )
   (item "ja/dom/selection")
   (subsection
    (item "ja/dom/selection/addrange")
    (item "ja/dom/selection/anchornode")
    (item "ja/dom/selection/anchoroffset")
    (item "ja/dom/selection/collapse")
    (item "ja/dom/selection/collapsetoend")
    (item "ja/dom/selection/collapsetostart")
    (item "ja/dom/selection/containsnode")
    (item "ja/dom/selection/deletefromdocument")
    (item "ja/dom/selection/extend")
    (item "ja/dom/selection/focusnode")
    (item "ja/dom/selection/focusoffset")
    (item "ja/dom/selection/getrangeat")
    (item "ja/dom/selection/iscollapsed")
    (item "ja/dom/selection/rangecount")
    (item "ja/dom/selection/removeallranges")
    (item "ja/dom/selection/removerange")
    (item "ja/dom/selection/selectallchildren")
    (item "ja/dom/selection/tostring")
    )
   (item "ja/dom/style")
   (subsection
    (item "ja/dom/style.media")
    (item "ja/dom/style.type")
    )
   (item "ja/dom/stylesheet")
   (subsection
    (item "ja/dom/stylesheet.cssrules")
    (item "ja/dom/stylesheet.deleterule")
    (item "ja/dom/stylesheet.disabled")
    (item "ja/dom/stylesheet.href")
    (item "ja/dom/stylesheet.insertrule")
    (item "ja/dom/stylesheet.media")
    (item "ja/dom/stylesheet.ownernode")
    (item "ja/dom/stylesheet.ownerrule")
    (item "ja/dom/stylesheet.parentstylesheet")
    (item "ja/dom/stylesheet.title")
    (item "ja/dom/stylesheet.type")
    )
   (item "ja/dom/treewalker")
   (subsection
    (item "ja/dom/treewalker.filter")
    (item "ja/dom/treewalker.root")
    (item "ja/dom/treewalker.whattoshow")
    )
   (item "ja/dom/window")
   (subsection
    (item "ja/dom/window.alert")
    (item "ja/dom/window.applicationcache")
    (item "ja/dom/window.atob")
    (item "ja/dom/window.back")
    (item "ja/dom/window.blur")
    (item "ja/dom/window.btoa")
    (item "ja/dom/window.captureevents")
    (item "ja/dom/window.clearinterval")
    (item "ja/dom/window.cleartimeout")
    (item "ja/dom/window.close")
    (item "ja/dom/window.closed")
    (item "ja/dom/window.confirm")
    (item "ja/dom/window.content")
    (item "ja/dom/window.controllers")
    (item "ja/dom/window.crypto")
    (item "ja/dom/window.defaultstatus")
    (item "ja/dom/window.dialogarguments")
    (item "ja/dom/window.directories")
    (item "ja/dom/window.dispatchevent")
    (item "ja/dom/window.document")
    (item "ja/dom/window.dump")
    (item "ja/dom/window.escape")
    (item "ja/dom/window.find")
    (item "ja/dom/window.focus")
    (item "ja/dom/window.forward")
    (item "ja/dom/window.frameelement")
    (item "ja/dom/window.frames")
    (item "ja/dom/window.fullscreen")
    (item "ja/dom/window.geckoactivexobject")
    (item "ja/dom/window.getattention")
    (item "ja/dom/window.getcomputedstyle")
    (item "ja/dom/window.getselection")
    (item "ja/dom/window.history")
    (item "ja/dom/window.home")
    (item "ja/dom/window.importdialog")
    (item "ja/dom/window.innerheight")
    (item "ja/dom/window.innerwidth")
    (item "ja/dom/window.length")
    (item "ja/dom/window.location")
    (item "ja/dom/window.locationbar")
    (item "ja/dom/window.menubar")
    (item "ja/dom/window.moveby")
    (item "ja/dom/window.moveto")
    (item "ja/dom/window.mozinnerscreenx")
    (item "ja/dom/window.mozinnerscreeny")
    (item "ja/dom/window.mozscreenpixelspercsspixel")
    (item "ja/dom/window.name")
    (item "ja/dom/window.navigator.appcodename")
    (item "ja/dom/window.navigator.appname")
    (item "ja/dom/window.navigator.appversion")
    (item "ja/dom/window.navigator.buildid")
    (item "ja/dom/window.navigator.cookieenabled")
    (item "ja/dom/window.navigator.javaenabled")
    (item "ja/dom/window.navigator.language")
    (item "ja/dom/window.navigator.mimetypes")
    (item "ja/dom/window.navigator.mozislocallyavailable")
    (item "ja/dom/window.navigator.online")
    (item "ja/dom/window.navigator.oscpu")
    (item "ja/dom/window.navigator.platform")
    (item "ja/dom/window.navigator.plugins")
    (item "ja/dom/window.navigator.product")
    (item "ja/dom/window.navigator.productsub")
    (item "ja/dom/window.navigator.registercontenthandler")
    (item "ja/dom/window.navigator.registerprotocolhandler")
    (item "ja/dom/window.navigator")
    (item "ja/dom/window.navigator.useragent")
    (item "ja/dom/window.navigator.vendor")
    (item "ja/dom/window.navigator.vendorsub")
    (item "ja/dom/window.onabort")
    (item "ja/dom/window.onbeforeunload")
    (item "ja/dom/window.onblur")
    (item "ja/dom/window.onchange")
    (item "ja/dom/window.onclick")
    (item "ja/dom/window.onclose")
    (item "ja/dom/window.oncontextmenu")
    (item "ja/dom/window.ondragdrop")
    (item "ja/dom/window.onerror")
    (item "ja/dom/window.onfocus")
    (item "ja/dom/window.onhashchange")
    (item "ja/dom/window.onkeydown")
    (item "ja/dom/window.onkeypress")
    (item "ja/dom/window.onkeyup")
    (item "ja/dom/window.onload")
    (item "ja/dom/window.onmousedown")
    (item "ja/dom/window.onmousemove")
    (item "ja/dom/window.onmouseout")
    (item "ja/dom/window.onmouseover")
    (item "ja/dom/window.onmouseup")
    (item "ja/dom/window.onmozorientation")
    (item "ja/dom/window.onpaint")
    (item "ja/dom/window.onpopstate")
    (item "ja/dom/window.onreset")
    (item "ja/dom/window.onresize")
    (item "ja/dom/window.onscroll")
    (item "ja/dom/window.onselect")
    (item "ja/dom/window.onsubmit")
    (item "ja/dom/window.onunload")
    (item "ja/dom/window.open")
    (item "ja/dom/window.opendialog")
    (item "ja/dom/window.opener")
    (item "ja/dom/window.outerheight")
    (item "ja/dom/window.outerwidth")
    (item "ja/dom/window.parent")
    (item "ja/dom/window.personalbar")
    (item "ja/dom/window.pkcs11")
    (item "ja/dom/window.postmessage")
    (item "ja/dom/window.print")
    (item "ja/dom/window.prompt")
    (item "ja/dom/window.prompter")
    (item "ja/dom/window.queryinterface")
    (item "ja/dom/window.releaseevents")
    (item "ja/dom/window.resizeby")
    (item "ja/dom/window.resizeto")
    (item "ja/dom/window.routeevent")
    (item "ja/dom/window.screen.availheight")
    (item "ja/dom/window.screen.availleft")
    (item "ja/dom/window.screen.availtop")
    (item "ja/dom/window.screen.availwidth")
    (item "ja/dom/window.screen.colordepth")
    (item "ja/dom/window.screen.height")
    (item "ja/dom/window.screen.left")
    (item "ja/dom/window.screen.pixeldepth")
    (item "ja/dom/window.screen")
    (item "ja/dom/window.screen.top")
    (item "ja/dom/window.screen.width")
    (item "ja/dom/window.screenx")
    (item "ja/dom/window.screeny")
    (item "ja/dom/window.scroll")
    (item "ja/dom/window.scrollbars")
    (item "ja/dom/window.scrollby")
    (item "ja/dom/window.scrollbylines")
    (item "ja/dom/window.scrollbypages")
    (item "ja/dom/window.scrollmaxx")
    (item "ja/dom/window.scrollmaxy")
    (item "ja/dom/window.scrollto")
    (item "ja/dom/window.scrollx")
    (item "ja/dom/window.scrolly")
    (item "ja/dom/window.self")
    (item "ja/dom/window.setcursor")
    (item "ja/dom/window.setinterval")
    (item "ja/dom/window.settimeout")
    (item "ja/dom/window.showmodaldialog")
    (item "ja/dom/window.sidebar")
    (item "ja/dom/window.sizetocontent")
    (item "ja/dom/window.status")
    (item "ja/dom/window.statusbar")
    (item "ja/dom/window.stop")
    (item "ja/dom/window.toolbar")
    (item "ja/dom/window.top")
    (item "ja/dom/window.unescape")
    (item "ja/dom/window.updatecommands")
    (item "ja/dom/window.window")
    (item "ja/dom/window.xpcsafejsobjectwrapper")
    )

   (item "ja/dom/html")
   (subsection
    (item "ja/dom/html.version")
    )
   (item "ja/dom/htmlbodyelement")
   (item "ja/dom/htmlcollection")
   (item "ja/dom/htmloptionscollection")
   (item "ja/dom/head")
   (item "ja/dom/link")
   (item "ja/dom/meta")
   (item "ja/dom/form")
   (subsection
    (item "ja/dom/form.acceptcharset")
    (item "ja/dom/form.action")
    (item "ja/dom/form.elements")
    (item "ja/dom/form.encoding")
    (item "ja/dom/form.enctype")
    (item "ja/dom/form.length")
    (item "ja/dom/form.method")
    (item "ja/dom/form.name")
    (item "ja/dom/form.reset")
    (item "ja/dom/form.submit")
    (item "ja/dom/form.target")
    )
   (item "ja/dom/image")
   (item "ja/dom/input")
   (subsection
    (item "ja/dom/input.mozgetfilenamearray")
    (item "ja/dom/input.mozsetfilenamearray")
    (item "ja/dom/input.multiple")
    )
   (item "ja/dom/select")
   (subsection
    (item "ja/dom/select.add")
    (item "ja/dom/select.remove")
    (item "ja/dom/select.type")
    )
   (item "ja/dom/table")
   (subsection
    (item "ja/dom/table.align")
    (item "ja/dom/table.bgcolor")
    (item "ja/dom/table.border")
    (item "ja/dom/table.caption")
    (item "ja/dom/table.cellpadding")
    (item "ja/dom/table.cellspacing")
    (item "ja/dom/table.createcaption")
    (item "ja/dom/table.createtfoot")
    (item "ja/dom/table.createthead")
    (item "ja/dom/table.deletecaption")
    (item "ja/dom/table.deleterow")
    (item "ja/dom/table.deletetfoot")
    (item "ja/dom/table.deletethead")
    (item "ja/dom/table.frame")
    (item "ja/dom/table.insertrow")
    (item "ja/dom/table.rows")
    (item "ja/dom/table.rules")
    (item "ja/dom/table.summary")
    (item "ja/dom/table.tbodies")
    (item "ja/dom/table.tfoot")
    (item "ja/dom/table.thead")
    (item "ja/dom/table.width")
    )
   (item "ja/dom/tablerow")
   (subsection
    (item "ja/dom/tablerow.insertcell")
    )
   (item "ja/dom/text")
   (subsection
    (item "ja/dom/text.iselementcontentwhitespace")
    (item "ja/dom/text.replacewholetext")
    (item "ja/dom/text.splittext")
    (item "ja/dom/text.wholetext")
    )
   (item "ja/dom/textarea")
   (item "ja/dom/title")
   )
  )
 (chapter
  (item "ja/html")
  (section
   (item "ja/html/canvas")
   (subsection
    (item "ja/html/canvas/pixel_manipulation_with_canvas")
    )
   (item "ja/html/element")
   (subsection
    (item "ja/html/element/a")
    (item "ja/html/element/abbr")
    (item "ja/html/element/acronym")
    (item "ja/html/element/address")
    (item "ja/html/element/applet")
    (item "ja/html/element/area")
    (item "ja/html/element/audio")
    (item "ja/html/element/b")
    (item "ja/html/element/base")
    (item "ja/html/element/basefont")
    (item "ja/html/element/bdo")
    (item "ja/html/element/bgsound")
    (item "ja/html/element/big")
    (item "ja/html/element/blink")
    (item "ja/html/element/blockquote")
    (item "ja/html/element/br")
    (item "ja/html/element/canvas")
    (item "ja/html/element/center")
    (item "ja/html/element/cite")
    (item "ja/html/element/code")
    (item "ja/html/element/col")
    (item "ja/html/element/colgroup")
    (item "ja/html/element/comment")
    (item "ja/html/element/dd")
    (item "ja/html/element/dl")
    (item "ja/html/element/dt")
    (item "ja/html/element/em")
    (item "ja/html/element/h1_h2_h3_h4_h5_h6")
    (item "ja/html/element/hr")
    (item "ja/html/element/html")
    (item "ja/html/element/i")
    (item "ja/html/element/iframe")
    (item "ja/html/element/img")
    (item "ja/html/element/kbd")
    (item "ja/html/element/keygen")
    (item "ja/html/element/li")
    (item "ja/html/element/link")
    (item "ja/html/element/marquee")
    (item "ja/html/element/ol")
    (item "ja/html/element/p")
    (item "ja/html/element/q")
    (item "ja/html/element/s")
    (item "ja/html/element/samp")
    (item "ja/html/element/script")
    (item "ja/html/element/small")
    (item "ja/html/element/source")
    (item "ja/html/element/strong")
    (item "ja/html/element/tt")
    (item "ja/html/element/ul")
    (item "ja/html/element/video")
    )
   (item "ja/html/inline_elements")
   (item "ja/html/block-level_elements")
   (item "ja/html/html5")
   (item "ja/html/introduction_to_html5")
   (item "ja/html/html_extensions")
   (item "ja/html/community")
   )
  )
 (chapter
  (item "ja/css")
  (section
   (item "ja/css_reference")
   (subsection
    (item "ja/css_reference/mozilla_extensions")
    (subsubsection
     (item "ja/css/-moz-alias")
     (item "ja/css/-moz-appearance")
     (item "ja/css/-moz-background-clip")
     (item "ja/css/-moz-background-inline-policy")
     (item "ja/css/-moz-background-origin")
     (item "ja/css/-moz-background-size")
     (item "ja/css/-moz-binding")
     (item "ja/css/-moz-border-bottom-colors")
     (item "ja/css/-moz-border-image")
     (item "ja/css/-moz-border-left-colors")
     (item "ja/css/-moz-border-radius-bottomleft")
     (item "ja/css/-moz-border-radius-bottomright")
     (item "ja/css/-moz-border-radius-topleft")
     (item "ja/css/-moz-border-radius-topright")
     (item "ja/css/-moz-border-radius")
     (item "ja/css/-moz-border-right-colors")
     (item "ja/css/-moz-border-top-colors")
     (item "ja/css/-moz-box-align")
     (item "ja/css/-moz-box-direction")
     (item "ja/css/-moz-box-flex")
     (item "ja/css/-moz-box-ordinal-group")
     (item "ja/css/-moz-box-orient")
     (item "ja/css/-moz-box-pack")
     (item "ja/css/-moz-box-shadow")
     (item "ja/css/-moz-box-sizing")
     (item "ja/css/-moz-cell")
     (item "ja/css/-moz-column-count")
     (item "ja/css/-moz-column-gap")
     (item "ja/css/-moz-column-rule-color")
     (item "ja/css/-moz-column-rule-style")
     (item "ja/css/-moz-column-rule-width")
     (item "ja/css/-moz-column-rule")
     (item "ja/css/-moz-column-width")
     (item "ja/css/-moz-context-menu")
     (item "ja/css/-moz-copy")
     (item "ja/css/-moz-float-edge")
     (item "ja/css/-moz-force-broken-image-icon")
     (item "ja/css/-moz-grab")
     (item "ja/css/-moz-grabbing")
     (item "ja/css/-moz-image-region")
     (item "ja/css/-moz-initial")
     (item "ja/css/-moz-linear-gradient")
     (item "ja/css/-moz-margin-end")
     (item "ja/css/-moz-margin-start")
     (item "ja/css/-moz-outline-color")
     (item "ja/css/-moz-outline-offset")
     (item "ja/css/-moz-outline-radius-bottomleft")
     (item "ja/css/-moz-outline-radius-bottomright")
     (item "ja/css/-moz-outline-radius-topleft")
     (item "ja/css/-moz-outline-radius-topright")
     (item "ja/css/-moz-outline-radius")
     (item "ja/css/-moz-outline-style")
     (item "ja/css/-moz-outline-width")
     (item "ja/css/-moz-outline")
     (item "ja/css/-moz-padding-end")
     (item "ja/css/-moz-padding-start")
     (item "ja/css/-moz-radial-gradient")
     (item "ja/css/-moz-repeating-linear-gradient")
     (item "ja/css/-moz-repeating-radial-gradient")
     (item "ja/css/-moz-spinning")
     (item "ja/css/-moz-stack-sizing")
     (item "ja/css/-moz-transform-origin")
     (item "ja/css/-moz-transform")
     (item "ja/css/-moz-transition-delay")
     (item "ja/css/-moz-transition-duration")
     (item "ja/css/-moz-transition-property")
     (item "ja/css/-moz-transition-timing-function")
     (item "ja/css/-moz-transition")
     (item "ja/css/-moz-user-focus")
     (item "ja/css/-moz-user-input")
     (item "ja/css/-moz-user-select")
     (item "ja/css/-moz-window-shadow")
     (item "ja/css/-moz-zoom-in")
     (item "ja/css/-moz-zoom-out")
     (item "ja/css/_-moz-alt-text")
     (item "ja/css/_-moz-broken")
     (item "ja/css/_-moz-document")
     (item "ja/css/_-moz-drag-over")
     (item "ja/css/_-moz-first-node")
     (item "ja/css/_-moz-last-node")
     (item "ja/css/_-moz-list-bullet")
     (item "ja/css/_-moz-locale-dir(ltr)")
     (item "ja/css/_-moz-locale-dir(rtl)")
     (item "ja/css/_-moz-lwtheme-brighttext")
     (item "ja/css/_-moz-lwtheme-darktext")
     (item "ja/css/_-moz-lwtheme")
     (item "ja/css/_-moz-only-whitespace")
     (item "ja/css/_-moz-placeholder")
     (item "ja/css/_-moz-system-metric(images-in-menus)")
     (item "ja/css/_-moz-system-metric(mac-graphite-theme)")
     (item "ja/css/_-moz-system-metric(scrollbar-end-backward)")
     (item "ja/css/_-moz-system-metric(scrollbar-end-forward)")
     (item "ja/css/_-moz-system-metric(scrollbar-start-backward)")
     (item "ja/css/_-moz-system-metric(scrollbar-start-forward)")
     (item "ja/css/_-moz-system-metric(scrollbar-thumb-proportional)")
     (item "ja/css/_-moz-system-metric(touch-enabled)")
     (item "ja/css/_-moz-system-metric(windows-default-theme)")
     (item "ja/css/_-moz-tree-cell-text(hover)")
     (item "ja/css/_-moz-tree-cell-text")
     (item "ja/css/_-moz-tree-cell")
     (item "ja/css/_-moz-tree-column")
     (item "ja/css/_-moz-tree-drop-feedback")
     (item "ja/css/_-moz-tree-image")
     (item "ja/css/_-moz-tree-indentation")
     (item "ja/css/_-moz-tree-line")
     (item "ja/css/_-moz-tree-progressmeter")
     (item "ja/css/_-moz-tree-row(hover)")
     (item "ja/css/_-moz-tree-row")
     (item "ja/css/_-moz-tree-separator")
     (item "ja/css/_-moz-tree-twisty")
     (item "ja/css/_-moz-window-inactive")
     (item "ja/css/__-moz-selection")
     )
    (item "ja/css_reference/property_template")
    )
   (item "ja/css_support_charts")
   (item "ja/css-2_quick_reference")
   (subsection
    (item "ja/css-2_quick_reference/all_in_a_page")
    (item "ja/css-2_quick_reference/box_model")
    (item "ja/css-2_quick_reference/color_and_background")
    (item "ja/css-2_quick_reference/font")
    (item "ja/css-2_quick_reference/lists")
    (item "ja/css-2_quick_reference/selectors")
    (item "ja/css-2_quick_reference/tables")
    (item "ja/css-2_quick_reference/text")
    (item "ja/css-2_quick_reference/units")
    (item "ja/css-2_quick_reference/user_interface")
    (item "ja/css-2_quick_reference/visual_effects")
    (item "ja/css-2_quick_reference/visual_formatting_details")
    (item "ja/css-2_quick_reference/visual_formatting_model")
    )
   (item "ja/css3_columns")
   (item "ja/css_counters")
   (item "ja/css_improvements_in_firefox_3")
   (item "ja/css/adjacent_sibling_selectors")
   (item "ja/css/attribute_selectors")
   (item "ja/css/block_formatting_context")
   (item "ja/css/box_model")
   (item "ja/css/child_selectors")
   (item "ja/css/class_selectors")
   (item "ja/css/css_transform_functions")
   (item "ja/css/css_transitions")
   (item "ja/css/descendant_selectors")
   (item "ja/css/faq")
   (item "ja/css/general_sibling_selectors")
   (item "ja/css/id_selectors")
   (item "ja/css/length")
   (item "ja/css/margin_collapsing")
   (item "ja/css/multiple_backgrounds")
   (item "ja/css/media")
   (subsection
    (item "ja/css/media/bitmap")
    (item "ja/css/media/tactile")
    (item "ja/css/media/tv")
    (item "ja/css/media/visual")
    )
   (item "ja/css/media_queries")
   (item "ja/css/other_resources")
   (item "ja/css/scaling_background_images")
   (item "ja/css/type_selectors")
   (item "ja/css/universal_selectors")
   (item "ja/css/writing_efficient_css")
   (item "ja/css/__first-letter")
   (item "ja/css/__first-line")
   (item "ja/css/__selection")
   (item "ja/css/_active")
   (item "ja/css/_after")
   (item "ja/css/_before")
   (item "ja/css/_checked")
   (item "ja/css/_default")
   (item "ja/css/_disabled")
   (item "ja/css/_empty")
   (item "ja/css/_enabled")
   (item "ja/css/_first-child")
   (item "ja/css/_first-of-type")
   (item "ja/css/_focus")
   (item "ja/css/_hover")
   (item "ja/css/_indeterminate")
   (item "ja/css/_lang")
   (item "ja/css/_last-child")
   (item "ja/css/_last-of-type")
   (item "ja/css/_link")
   (item "ja/css/_not")
   (item "ja/css/_nth-child")
   (item "ja/css/_nth-last-child")
   (item "ja/css/_nth-last-of-type")
   (item "ja/css/_nth-of-type")
   (item "ja/css/_only-of-type")
   (item "ja/css/_root")
   (item "ja/css/_target")
   (item "ja/css/_visited")
   (item "ja/css/_font-face")
   (item "ja/css/_import")
   (item "ja/css/_media")
   (item "ja/css/alias")
   (item "ja/css/angle")
   (item "ja/css/aural")
   (item "ja/css/auto")
   (item "ja/css/azimuth")
   (item "ja/css/background-attachment")
   (item "ja/css/background-color")
   (item "ja/css/background-image")
   (item "ja/css/background-position")
   (item "ja/css/background-repeat")
   (item "ja/css/background")
   (item "ja/css/border-bottom-color")
   (item "ja/css/border-bottom-style")
   (item "ja/css/border-bottom-width")
   (item "ja/css/border-bottom")
   (item "ja/css/border-collapse")
   (item "ja/css/border-color")
   (item "ja/css/border-image")
   (item "ja/css/border-left-color")
   (item "ja/css/border-left-style")
   (item "ja/css/border-left-width")
   (item "ja/css/border-left")
   (item "ja/css/border-right-color")
   (item "ja/css/border-right-style")
   (item "ja/css/border-right-width")
   (item "ja/css/border-right")
   (item "ja/css/border-spacing")
   (item "ja/css/border-style")
   (item "ja/css/border-top-color")
   (item "ja/css/border-top-style")
   (item "ja/css/border-top-width")
   (item "ja/css/border-top")
   (item "ja/css/border-width")
   (item "ja/css/border")
   (item "ja/css/bottom")
   (item "ja/css/box-shadow")
   (item "ja/css/box-sizing")
   (item "ja/css/caption-side")
   (item "ja/css/clear")
   (item "ja/css/clip")
   (item "ja/css/color")
   (item "ja/css/color_value")
   (item "ja/css/computed_value")
   (item "ja/css/content")
   (item "ja/css/counter-increment")
   (item "ja/css/counter-reset")
   (item "ja/css/counter")
   (item "ja/css/currentcolor")
   (item "ja/css/cursor")
   (item "ja/css/direction")
   (item "ja/css/display")
   (item "ja/css/empty-cells")
   (item "ja/css/float")
   (item "ja/css/font-family")
   (item "ja/css/font-size-adjust")
   (item "ja/css/font-size")
   (item "ja/css/font-stretch")
   (item "ja/css/font-style")
   (item "ja/css/font-variant")
   (item "ja/css/font-weight")
   (item "ja/css/font")
;; FIXME
;;    (item "ja/css/getting_started")
;;    (subsection
;;     (item "ja/css/getting_started/boxes")
;;     (item "ja/css/getting_started/cascading_and_inheritance")
;;     (item "ja/css/getting_started/color")
;;     (item "ja/css/getting_started/content")
;;     (item "ja/css/getting_started/how_css_works")
;;     (item "ja/css/getting_started/javascript")
;;     (item "ja/css/getting_started/layout")
;;     (item "ja/css/getting_started/lists")
;;     (item "ja/css/getting_started/media")
;;     (item "ja/css/getting_started/readable_css")
;;     (item "ja/css/getting_started/selectors")
;;     (item "ja/css/getting_started/svg_graphics")
;;     (item "ja/css/getting_started/tables")
;;     (item "ja/css/getting_started/text_styles")
;;     (item "ja/css/getting_started/what_is_css")
;;     (item "ja/css/getting_started/why_use_css")
;;     (item "ja/css/getting_started/why_use_css?")
;;     (item "ja/css/getting_started/xbl_bindings")
;;     (item "ja/css/getting_started/xml_data")
;;     (item "ja/css/getting_started/xul_user_interfaces")
;;     )
   (item "ja/css/height")
   (item "ja/css/hidden")
   (item "ja/css/image-rendering")
   (item "ja/css/ime-mode")
   (item "ja/css/inherit")
   (item "ja/css/inheritance")
   (item "ja/css/initial")
   (item "ja/css/initial_value")
   (item "ja/css/integer")
   (item "ja/css/interactive")
   (item "ja/css/left")
   (item "ja/css/letter-spacing")
   (item "ja/css/line-height")
   (item "ja/css/list-style-image")
   (item "ja/css/list-style-position")
   (item "ja/css/list-style-type")
   (item "ja/css/list-style")
   (item "ja/css/margin-bottom")
   (item "ja/css/margin-left")
   (item "ja/css/margin-right")
   (item "ja/css/margin-top")
   (item "ja/css/margin")
   (item "ja/css/max-height")
   (item "ja/css/max-width")
   (item "ja/css/min-height")
   (item "ja/css/min-width")
   (item "ja/css/none")
   (item "ja/css/normal")
   (item "ja/css/number")
   (item "ja/css/opacity")
   (item "ja/css/outline-color")
   (item "ja/css/outline-offset")
   (item "ja/css/outline-style")
   (item "ja/css/outline-width")
   (item "ja/css/outline")
   (item "ja/css/overflow-x")
   (item "ja/css/overflow-y")
   (item "ja/css/overflow")
   (item "ja/css/padding-bottom")
   (item "ja/css/padding-left")
   (item "ja/css/padding-right")
   (item "ja/css/padding-top")
   (item "ja/css/padding")
   (item "ja/css/percentage")
   (item "ja/css/pointer-events")
   (item "ja/css/position")
   (item "ja/css/quotes")
   (item "ja/css/resolution")
   (item "ja/css/right")
   (item "ja/css/shape")
   (item "ja/css/string")
   (item "ja/css/table-layout")
   (item "ja/css/text-align")
   (item "ja/css/text-decoration")
   (item "ja/css/text-indent")
   (item "ja/css/text-overflow")
   (item "ja/css/text-rendering")
   (item "ja/css/text-shadow")
   (item "ja/css/text-transform")
   (item "ja/css/top")
   (item "ja/css/uri")
   (item "ja/css/using_css_transforms")
   (item "ja/css/vertical-align")
   (item "ja/css/visibility")
   (item "ja/css/visible")
   (item "ja/css/white-space")
   (item "ja/css/width")
   (item "ja/css/word-spacing")
   (item "ja/css/word-wrap")
   (item "ja/css/z-index")
   )
  )
 (chapter
  (item "ja/canvas_tutorial")
  (section
   (item "ja/canvas_tutorial/compositing")
   (item "ja/canvas_tutorial/basic_usage")
   (item "ja/canvas_tutorial/transformations")
   (item "ja/canvas_tutorial/applying_styles_and_colors")
   (item "ja/canvas_tutorial/using_images")
   (item "ja/canvas_tutorial/drawing_shapes")
   (item "ja/canvas_tutorial/basic_animations")
   )
  )
 (chapter
  (item "ja/e4x")
  (section
   (item "ja/e4x/processing_xml_with_e4x")
   )
  )
 (chapter
  (item "ja/e4x_tutorial")
  (section
   (item "ja/e4x_tutorial/introduction")
   (item "ja/e4x_tutorial/accessing_xml_children")
   (item "ja/e4x_tutorial/descendants_and_filters")
   (item "ja/e4x_tutorial/namespaces")
   (item "ja/e4x_tutorial/the_global_xml_object")
   )
  )
 (chapter
  (item "ja/firefox_for_developers")
  (section
   (item "ja/firefox_1.5_for_developers")
   (item "ja/firefox_2_for_developers")
   (item "ja/firefox_3.5_for_developers")
   (item "ja/firefox_3.6_for_developers")
   (item "ja/firefox_3_for_developers")
   )
  )
 )
