\input texinfo  @c -*-texinfo-*-
@comment %**start of header
@setfilename ultimate.info
@settitle Mozilla Developer Center Ultimate Collection
@documentencoding utf-8

@comment %**end of header

@iftex
@finalout
@parskip 4pt plus 1pt
@end iftex

@titlepage
@title Mozilla Developer Center Ultimate Collection
@subtitle version 1.0
@author Mozilla Developer Center (http://developer.mozilla.org/)

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2010 Mozilla Developer Center (http://developer.mozilla.org/)

@end titlepage

@node Top, , (dir), (dir)
@top Mozilla Developer Center Ultimate Collection

@menu
* ja/core_javascript_1.5_guide ::
* ja/core_javascript_1.5_reference ::
* ja/new_in_javascript ::
* ja/gecko_dom_reference ::
* ja/dom ::
* ja/html ::
* ja/css ::
* ja/canvas_tutorial ::
* ja/e4x ::
* ja/e4x_tutorial ::
* ja/firefox_for_developers ::
* ja/Ultimate Index::
@end menu

@include includes.texi

@node ja/Ultimate Index,,ja/firefox_for_developers,Top
@appendix 索引
@printindex fn
@contents
@bye
